### ISSUE TITLE
Multiple Path Optional Parameters generates Invalid Path error

### ISSUE THREAD

**Issue by stongo** [hapijs/hapi#1010]
When adding a route path with multiple optional params, invalid path error is generated

Error: Invalid path: /producers/{town?}/{food?}
    at Object.exports.assert (/Users/marcusstong/htdocs/fresh/site/node_modules/Hapi/node_modules/hoek/lib/index.js:367:15)
    at new module.exports.internals.Route (/Users/marcusstong/htdocs/fresh/site/node_modules/Hapi/lib/route.js:44:11)
    at /Users/marcusstong/htdocs/fresh/site/node_modules/Hapi/lib/router.js:83:21
    at Array.forEach (native)
    at internals.Router.add (/Users/marcusstong/htdocs/fresh/site/node_modules/Hapi/lib/router.js:81:13)
    at internals.Server._route (/Users/marcusstong/htdocs/fresh/site/node_modules/Hapi/lib/server.js:279:18)
    at internals.Server.route.internals.Server.addRoute.internals.Server.addRoutes (/Users/marcusstong/htdocs/fresh/site/node_modules/Hapi/lib/server.js:273:10)
    at Object.<anonymous> (/Users/marcusstong/htdocs/fresh/site/index.js:37:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by epavlenko** [comment]
But what can I do in my situation?
I have 2 languages on a website - English (en) and Spanish (es).
I want to use the following urls for these languages:

 - English: http://domain.com/page-slug
 - Spanish: http://domain.com/es/page-slug

I need one route for both patterns to use named routes to generate an URL for a link to a page, so I cannot create two different routes for '/{page}' and '/{lang}/{page}'.

**Comment by codycraven** [comment]
@epavlenko, I see most multi-lingual sites use separate subdomains or the default site language (en in your case) also receives the language code in the URL.

**Comment by epavlenko** [comment]
I'm developing a new version of an existing website and I need to preserve URL structure fully in order to keep current positions in search engines and not to loose traffic.

**Comment by codycraven** [comment]
@epavlenko If you really can not do 301 redirects to preserve value, then you'll probably need to proxy your requests through another system before Hapi.

I unfortunately don't think you'll get a more satisfactory answer. Hapi is very up front in the documentation that this use case is not supported by Hapi's route system.

**Comment by hueniverse** [comment]
Just create two routes and reuse the config object.

**Comment by ignivamahesh** [comment]
Hi, I am learning hapi.js here my question is if there is a requirement to do this type of route. then how will do it?
