### ISSUE TITLE
plugin emitting an event throws error

### ISSUE THREAD

**Issue by wraithgar** [hapijs/hapi#2115]
Starting with version 7.2.0 when a plugin emits a log event this error is thrown.

```
Debug: hapi, internal, implementation, error 
    TypeError: Uncaught error: Cannot read property '_events' of undefined
    at Moonboots.internals.Plugin.log (/[...]/node_modules/hapi/lib/plugin.js:274:27)
    at Moonboots.emit (events.js:98:17)
```

**Comment by flushentitypacket** [comment]
I hit this issue as well.

@hueniverse is correct, but for folks who are still lost, an easy fix:

```
emitter.on('log', plugin.log.bind(plugin));
```

This would fix the code posted by @wraithgar
