### ISSUE TITLE
Route response validation 500 error

### ISSUE THREAD

**Issue by AndrewKeig** [hapijs/hapi#2293]
"hapi": "^8.0.0",
"joi": "^5.0.2",

Hi

I am trying to get response validation rules working.  My route is returning the following response:

```
{
    "_id" : ObjectId("542eda61d51db6ed71000018")
}
```

Here is my route:

```
server.route({ 
        method: 'GET', 
        path: '/users/{id}',
        handler: handlers.get, 
        config: { 
            response: { schema: true }
        }
    });

```

If I set config:response:schema to true, I get the correct response, no validation is performed.

If I set config:response:schema false I get the below 500 error, if I pass a joi object, I get the same error,  making it very difficult to debug issues with my validation object.

I am not sure if this is the intended behaviour, either way, would be great if we could get some better reporting on whats going on here.  

ERROR:

```


statusCode, message, data 500 &#x24;__ is not allowed. isNew is not allowed. errors is not allowed. _maxListeners is not allowed. _doc is not allowed. _pres is not allowed. _posts is not allowed. save is not allowed. _events is not allowed undefined
Debug: hapi, internal, implementation, error
    Error: &#x24;__ is not allowed. isNew is not allowed. errors is not allowed. _maxListeners is not allowed. _doc is not allowed. _pres is not allowed. _posts is not allowed. save is not allowed. _events is not allowed
    at Object.exports.create (+++/node_modules/hapi/node_modules/boom/lib/index.js:24:17)
    at Object.exports.internal (+++/node_modules/hapi/node_modules/boom/lib/index.js:249:92)
    at Object.exports.badImplementation (+++/node_modules/boom/lib/index.js:285:23)
    at postValidate (+++/node_modules/hapi/lib/validation.js:150:26)
    at internals.Any._validateWithOptions (+++/node_modules/hapi/node_modules/joi/lib/any.js:430:16)
    at root.validate (+++/node_modules/hapi/node_modules/joi/lib/index.js:102:23)

```

**Comment by prashaantt** [comment]
@2color  You should probably be setting the [`allowUnknown`](https://github.com/hapijs/joi#validatevalue-schema-options-callback) option to `true`.
