### ISSUE TITLE
options for Hapi.Server: router property is now allowed

### ISSUE THREAD

**Issue by paulovieira** [hapijs/hapi#2346]
I get an error with this trivial app (see output below):

```javascript
var Hapi = require('hapi');
var server = new Hapi.Server({
    router: {
        isCaseSensitive: true,
        stripTrailingSlash: false
    }
});
```
According to the documentation this should be a valid option. I'm using Hapi 8.0.

Error output:

```
/home/pvieira/github/clima-madeira/node_modules/hapi/node_modules/hoek/lib/index.js:663
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Invalid server options {
  "router" [1]: {
    "isCaseSensitive": true,
    "stripTrailingSlash": false
  }
}

[1] router is not allowed
    at Object.exports.assert (/home/pvieira/github/clima-madeira/node_modules/hapi/node_modules/hoek/lib/index.js:663:11)
    at Object.exports.assert (/home/pvieira/github/clima-madeira/node_modules/hapi/lib/schema.js:15:10)
    at new module.exports.internals.Server (/home/pvieira/github/clima-madeira/node_modules/hapi/lib/server.js:32:22)
    at Object.<anonymous> (/home/pvieira/github/clima-madeira/index.js:12:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

```

**Comment by gergoerdosi** [comment]
It belongs to connection settings.

```
var Hapi = require('hapi');

var server = new Hapi.Server({
    connections: {
        router: {
            isCaseSensitive: true,
            stripTrailingSlash: false
        }
    }
});
```

Where is the documentation you are referring to?

**Comment by paulovieira** [comment]
Sorry, my mistake!

The documentation is great, but many times I get lost in locating myself.

It would very cool if the user could have immediate feedback about the parent object of a given options. For instance, on hover on the option name, the documentation could highlight the whole parent object.
