### ISSUE TITLE
Improve error message when validation.payload is set but type is GET

### ISSUE THREAD

**Issue by wraithan** [hapijs/hapi#2347]
Currently you get an error looking like: 

```
/Users/wraithan/devel/javascript/alert-alpaca/node_modules/hapi/lib/route.js:126
Hoek.assert(!this.settings.validate.payload || this.settings.payload.parse, 'R
                                                                    ^
TypeError: Cannot read property 'parse' of null
    at new module.exports.internals.Route (/Users/wraithan/devel/javascript/alert-alpaca/node_modules/hapi/lib/route.js:126:73)
    at internals.Connection._addRoute (/Users/wraithan/devel/javascript/alert-alpaca/node_modules/hapi/lib/connection.js:344:17)
    at internals.Connection._route (/Users/wraithan/devel/javascript/alert-alpaca/node_modules/hapi/lib/connection.js:336:18)
    at internals.Plugin._apply (/Users/wraithan/devel/javascript/alert-alpaca/node_modules/hapi/lib/plugin.js:432:14)
    at internals.Plugin.route (/Users/wraithan/devel/javascript/alert-alpaca/node_modules/hapi/lib/plugin.js:407:10)
    at Object.<anonymous> (/Users/wraithan/devel/javascript/alert-alpaca/index.js:7:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

It looks like there used to be a nicer error that was removed in a refactor:

https://github.com/hapijs/hapi/commit/4299e9e7513da024e577f8a287431c4578a14d15#diff-f34e409694d3ba334dabbea190f64c1dL117

**Comment by gergoerdosi** [comment]
See this PR: https://github.com/hapijs/hapi/pull/2343

**Comment by wraithan** [comment]
@gergoerdosi Oh thanks! I didn't see an issue but I didn't look at the PRs. Not sure if you'll would rather keep the issue until the PR is closed or just close this out, either way is fine with me.
