### ISSUE TITLE
Object [object Object] has no method 'connection'

### ISSUE THREAD

**Issue by erikhemrick** [hapijs/hapi#2403]
The example on the tutorials page 'http://hapijs.com/tutorials' give the following error:

```
/home/eh/dev/src/sagan/hapi/myproject/app.js:5 server.connection({ port: 3000 });
       ^
TypeError: Object [object Object] has no method 'connection'
    at Object.<anonymous> (/home/eh/dev/src/sagan/hapi/myproject/app.js:5:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

```js
var Hapi = require('hapi');
var Good = require('good');

var server = new Hapi.Server();
server.connection({ port: 3000 });

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {
        reply('Hello, world!');
    }
});

server.route({
    method: 'GET',
    path: '/{name}',
    handler: function (request, reply) {
        reply('Hello, ' + encodeURIComponent(request.params.name) + '!');
    }
});

server.register({
    register: Good,
    options: {
        reporters: [{
            reporter: require('good-console'),
            args:[{ log: '*', response: '*' }]
        }]
    }
}, function (err) {
    if (err) {
        throw err; // something bad happened loading the plugin
    }

    server.start(function () {
        server.log('info', 'Server running at: ' + server.info.uri);
    });
});
```

**Comment by lloydbenson** [comment]
Are you sure you are using hapi 8.x?

**Comment by dp1140a** [comment]
I just encountered a similar error but with TypeError: Object #<Object> has no method 'route'.  I have tried removing my server.route methods and even having a blank server.js file and still get the same message.

**Comment by hueniverse** [comment]
This is not useful. We need code example and the version you are using.

**Comment by Pranay92** [comment]
I faced a similar issue as stated above and found out that I had hapi installed globally using `npm install -g hapi` and did not have any local installation and that's why I wasn't getting any error while `require('hapi')` but still an error on `server.connection()`. Hope this helps someone.
