### ISSUE TITLE
Bug with custom validation functions in the route options

### ISSUE THREAD

**Issue by gagle** [hapijs/hapi#2415]
Example:

```
/{foo}/
```

```javascript
{
  params: {
    foo: function (value, options, next) {
      next(null, true);
    }
  }
}
```

```
Error: Invalid schema content: 
    at Object.exports.assert (/vagrant/node_modules/hapi/node_modules/hoek/lib/index.js:663:11)
    at Object.exports.schema (/vagrant/node_modules/hapi/node_modules/joi/lib/cast.js:65:10)
    at internals.Object.keys (/vagrant/node_modules/hapi/node_modules/joi/lib/object.js:270:25)
    at Object.exports.schema (/vagrant/node_modules/hapi/node_modules/joi/lib/cast.js:46:33)
    at root.compile (/vagrant/node_modules/hapi/node_modules/joi/lib/index.js:113:21)
    at Object.internals.compileRule (/vagrant/node_modules/hapi/lib/route.js:256:88)
    at /vagrant/node_modules/hapi/lib/route.js:97:38
    at Array.forEach (native)
    at new module.exports.internals.Route (/vagrant/node_modules/hapi/lib/route.js:95:47)
    at internals.Connection._addRoute (/vagrant/node_modules/hapi/lib/connection.js:352:17)
```

The bug happens while [compiling the rule](https://github.com/hapijs/hapi/blob/9317fd1f1bb2fa4186284db57f89686c299faeb6/lib/route.js#L245).

The `rule` argument contains the object:

```
{
  foo: function (value, options, next) {
    next(null, true);
  }
}
```

`rule` is never a function, this piece of code is never executed:

```javascript
typeof rule === 'function' ? rule : ...
```

Instead, this is executed:

```javascript
... : Joi.compile(rule)
```

Therefore, this is what's being executed:

```javascript
Joi.compile({
  foo: function (value, options, next) {
    next(null, true);
  }
})
```

**Comment by hueniverse** [comment]
You can't specify validation functions for individual parameters. Either specify a function for `params` or a joi object.

**Comment by Marsup** [comment]
Or a mix of both, use joi inside your function and do further checks after joi validated.
