### ISSUE TITLE
Global Routes pre option error

### ISSUE THREAD

**Issue by tjsail33** [hapijs/hapi#2438]
When defining my server config as

```coffeescript
serverConfig = 
	app: 
		Information: Information
	cache: [
		{
			name: "sessionCache"
			engine: require('catbox-redis')
			host: redisUrl.hostname
			password: redisUrl.auth.split(":")[1] if redisUrl.auth?
			partition: "session"
		}
	]
	connections:
		load:
			maxEventLoopDelay: 3000
		routes:
			pre: [
				{
					method:'getAuthUser(auth)'
					assign:"user"
				}
			]
	load:
		sampleInterval: 5000
```

I receive a converting circular structure error as follows

```bash
[ERROR] 21:00:16 TypeError
TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at Error.internals.annotate (/Users/timcosta/chalkup/dev/node_modules/hapi/node_modules/joi/lib/errors.js:137:26)
  at Object.exports.assert (/Users/timcosta/chalkup/dev/node_modules/hapi/lib/schema.js:15:125)
  at new module.exports.internals.Server (/Users/timcosta/chalkup/dev/node_modules/hapi/lib/server.js:32:22)
  at Object.<anonymous> (/Users/timcosta/chalkup/dev/web.coffee:64:14)
  at Object.<anonymous> (/Users/timcosta/chalkup/dev/web.coffee:2:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/timcosta/chalkup/dev/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Object..coffee (/usr/local/lib/node_modules/node-dev/lib/hook.js:52:17)
  at Module.load (/Users/timcosta/chalkup/dev/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/timcosta/chalkup/dev/web-test.js:2:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Object..js (/usr/local/lib/node_modules/node-dev/lib/hook.js:52:17)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/node-dev/lib/wrap.js:51:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

The error goes away as soon as I remove the pre line from routes. Is this a bug in Hapi? I'm trying to assign my user object to the request object for every request without needing to use pre in every route definition, and this is the best way I have found so far but it doesn't seem to work.

**Comment by Marsup** [comment]
I've removed the `app` and `cache` parts but I get a `[1] "pre" is not allowed`, not your error.
Can you paste the output of `npm ls --depth=1` please ?

**Comment by tjsail33** [comment]
```bash
machine:folder username$ npm ls --depth=1
reponame@3.0.0 /path/to/repo
├─┬ algolia-search@1.7.5
│ ├── agentkeepalive@0.1.5
│ ├── buffers@0.1.1
│ └── underscore@1.4.4
├── async@0.9.0
├── bcryptjs@2.1.0
├─┬ bell@2.2.0
│ ├── cryptiles@2.0.4
│ ├── hoek@2.11.1
│ └── wreck@5.2.0
├─┬ boom@2.6.1
│ └── hoek@2.11.1
├─┬ catbox-redis@1.0.4
│ ├── hoek@2.11.1
│ └── redis@0.10.3
├─┬ code@1.3.0
│ └── hoek@2.11.1
├── coffee-script@1.9.1
├─┬ del@1.1.1
│ ├── each-async@1.1.1
│ ├── globby@1.2.0
│ ├── is-path-cwd@1.0.0
│ ├── is-path-in-cwd@1.0.0
│ ├── object-assign@2.0.0
│ └── rimraf@2.2.8
├─┬ google-oauth-jwt@0.1.4
│ └── debug@0.7.4
├─┬ gulp@3.8.11
│ ├── archy@1.0.0
│ ├── chalk@0.5.1
│ ├── deprecated@0.0.1
│ ├── gulp-util@3.0.4
│ ├── interpret@0.3.10
│ ├── liftoff@2.0.2
│ ├── minimist@1.1.0
│ ├── orchestrator@0.3.7
│ ├── pretty-hrtime@0.2.2
│ ├── semver@4.3.1
│ ├── tildify@1.0.0
│ ├── v8flags@2.0.2
│ └── vinyl-fs@0.3.13
├─┬ gulp-coffee@2.3.1
│ ├── gulp-util@3.0.4
│ ├── merge@1.2.0
│ ├── through2@0.6.3
│ └── vinyl-sourcemaps-apply@0.1.4
├─┬ gulp-css@0.1.0
│ ├── clean-css@2.0.8
│ └── through2@0.4.2
├─┬ gulp-less@3.0.1
│ ├── accord@0.15.2
│ ├── gulp-util@3.0.4
│ ├── object-assign@2.0.0
│ ├── through2@0.6.3
│ └── vinyl-sourcemaps-apply@0.1.4
├─┬ gulp-print@1.1.0
│ ├── colors@0.6.2
│ └── map-stream@0.1.0
├─┬ gulp-rev@3.0.1
│ ├── gulp-util@3.0.4
│ ├── object-assign@2.0.0
│ ├── through2@0.6.3
│ └── vinyl-file@1.1.1
├─┬ gulp-tap@0.1.3
│ └── event-stream@3.1.7
├─┬ gulp-uglify@1.1.0
│ ├── deepmerge@0.2.7
│ ├── gulp-util@3.0.4
│ ├── through2@0.6.3
│ ├── uglify-js@2.4.16
│ └── vinyl-sourcemaps-apply@0.1.4
├─┬ gulp-watch@4.1.1
│ ├── anymatch@1.1.0
│ ├── chokidar@1.0.0-rc3
│ ├── glob-parent@1.0.0
│ ├── gulp-util@3.0.4
│ ├── is-glob@1.1.1
│ ├── readable-stream@1.0.33
│ ├── vinyl@0.4.6
│ └── vinyl-file@1.1.1
├─┬ hapi@8.2.0
│ ├── accept@1.0.0
│ ├── ammo@1.0.0
│ ├── call@2.0.1
│ ├── catbox@4.2.1
│ ├── catbox-memory@1.1.1
│ ├── cryptiles@2.0.4
│ ├── h2o2@4.0.0
│ ├── heavy@3.0.0
│ ├── hoek@2.10.0
│ ├── inert@2.1.2
│ ├── iron@2.1.2
│ ├── items@1.1.0
│ ├── joi@5.0.2
│ ├── kilt@1.1.1
│ ├── mimos@2.0.2
│ ├── peekaboo@1.0.0
│ ├── qs@2.3.3
│ ├── shot@1.4.0
│ ├── statehood@2.0.0
│ ├── subtext@1.0.2
│ ├── topo@1.0.2
│ ├── vision@2.0.0
│ └── wreck@5.0.1
├─┬ hapi-auth-cookie@2.0.0
│ └── hoek@2.11.1
├── hapi-require-https@2.0.0
├─┬ jade@1.9.2
│ ├── character-parser@1.2.1
│ ├── commander@2.6.0
│ ├── constantinople@3.0.1
│ ├── mkdirp@0.5.0
│ ├── transformers@2.1.0
│ ├── void-elements@2.0.1
│ └── with@4.0.1
├─┬ joi@5.1.0
│ ├── hoek@2.11.1
│ ├── isemail@1.1.1
│ └── topo@1.0.2
├─┬ kue@0.8.11
│ ├── express@3.1.2
│ ├── jade@1.1.5
│ ├── lodash@2.4.1
│ ├── lodash-deep@1.5.3
│ ├── nib@0.5.0
│ ├── redis@0.10.3
│ ├── reds@0.2.5
│ └── stylus@0.42.2
├─┬ lab@5.3.0
│ ├── bossy@1.0.2
│ ├── diff@1.2.2
│ ├── eslint@0.14.1
│ ├── esprima@1.2.4
│ ├── handlebars@2.0.0
│ ├── hoek@2.11.1
│ ├── items@1.1.0
│ ├── jslint@0.7.3
│ └── source-map-support@0.2.9
├─┬ less@2.4.0
│ ├── errno@0.1.1
│ ├── graceful-fs@3.0.5
│ ├── image-size@0.3.5
│ ├── mime@1.3.4
│ ├── mkdirp@0.5.0
│ ├── promise@6.1.0
│ └── source-map@0.2.0
├── moment@2.9.0
├─┬ mongoose@3.8.24
│ ├── hooks@0.2.1
│ ├── mongodb@1.4.31
│ ├── mpath@0.1.1
│ ├── mpromise@0.4.3
│ ├── mquery@0.8.0
│ ├── ms@0.1.0
│ ├── muri@0.3.1
│ ├── regexp-clone@0.0.1
│ └── sliced@0.0.5
├─┬ mongoose-validate@0.0.5
│ └── validator@0.4.28
├─┬ mrhorse@0.0.3
│ ├── UNMET DEPENDENCY coveralls@^2.11.2
│ ├── hoek@2.10.0
│ └── lodash@2.4.1
├── node-uuid@1.4.2
├── redis@0.12.1
├─┬ request@2.53.0
│ ├── aws-sign2@0.5.0
│ ├── bl@0.9.4
│ ├── caseless@0.9.0
│ ├── combined-stream@0.0.7
│ ├── forever-agent@0.5.2
│ ├── form-data@0.2.0
│ ├── hawk@2.3.1
│ ├── http-signature@0.10.1
│ ├── isstream@0.1.1
│ ├── json-stringify-safe@5.0.0
│ ├── mime-types@2.0.9
│ ├── oauth-sign@0.6.0
│ ├── qs@2.3.3
│ ├── stringstream@0.0.4
│ ├── tough-cookie@0.12.1
│ └── tunnel-agent@0.4.0
├─┬ run-sequence@1.0.2
│ └── chalk@1.0.0
├─┬ sendgrid@1.6.0
│ ├── lodash@2.4.1
│ ├── mime@1.3.4
│ └── smtpapi@1.1.0
├─┬ slack-notify@0.1.4
│ ├── lodash@2.4.1
│ └── request@2.51.0
├── sugar@1.4.1
└─┬ twilio@1.11.1
  ├── jwt-simple@0.1.0
  ├── q@0.9.7
  ├── request@2.27.0
  ├── scmp@0.0.3
  └── underscore@1.8.2
```

**Comment by Marsup** [comment]
Everything seems up-to-date. I don't think this is because of the pre part, adding it just makes your config wrong, my error being the one you should see, but I guess the circular part comes from your app and/or cache parts. This is clearly a Joi issue so I'll close this one and continue there.
