### ISSUE TITLE
Installation Error - unauthorized User document conflicts

### ISSUE THREAD

**Issue by hegdeashwin** [hapijs/hapi#2448]
While installation of Hapi with ```sudo npm install Hapi``` 
i got the below error and installation failed. 
I am using Ubuntu OS 32 bit.
```
npm http GET https://registry.npmjs.org/accept/-/accept-1.0.0.tgz
npm ERR! Error: unauthorized User document conflicts must be resolved before the document is used for authentication purposes.: qs/2.3.3
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.8.0-19-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hapi"
npm ERR! cwd /media/hegdeashwin/My Passport/Storage-TB/OpenSource/Experiments/Hapi
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm http 200 https://registry.npmjs.org/topo/1.0.2
```
Is this error due to Nodejs version ?
```Engine hapi@8.2.0: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.21","npm":"1.3.11"})```

I think for Ubuntu 0.10.25 is the most stable version for node.js. So i upgraded my Nodejs version.
and I was able to install Hapi 8.2.0 version with ```sudo npm install hapi@8.2.0```. With 
```engine hapi@8.2.0: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.25","npm":"1.3.24"})```
configuration.

**Comment by hegdeashwin** [comment]
Closing this. Updating Nodejs; fixed the installation error.
