### ISSUE TITLE
How to reply from outside the route handler

### ISSUE THREAD

**Issue by gilly3** [hapijs/hapi#2489]
I want to defer the reply to my route by storing the `reply` function and calling it later.  When I try to do so, this always results in a 500 response being sent to the client, and this error being logged to the node console:

```
Debug: internal, implementation, error
    Error: Uncaught error: socket hang up
    at createHangUpError (_http_client.js:198:15)
    at Socket.socketOnEnd (_http_client.js:283:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickDomainCallback (node.js:388:13)
```

Here's my code:

```Javascript
var pendingReplies = {};
server.route({
    method: "POST",
    path: "/",
    handler: function (request, reply) {
        var id = generateUuid();
        pendingReplies[id] = reply;
    }
});
// reply later by calling this:
function sendResponse(id, data) {
    pendingReplies[id](data);
}
```

I also tried using `reply().hold()`:

```Javascript
var pendingReplies = {};
server.route({
    method: "POST",
    path: "/",
    handler: function (request, reply) {
        var response = reply().hold();
        pendingReplies[id] = function (data) {
            response.source = data;
            response.send();
        };
        return response;
    }
});
// reply later by calling this:
function sendResponse(id, data) {
    pendingReplies[id](data);
}
```

Is it possible to reply to a request asynchronously?

See this [question at stackoverflow.com](http://stackoverflow.com/q/29402797/361684)

**Comment by gilly3** [comment]
Nevermind... there was an error in my code causing this.  Fixed the error and it works the way I want when using `reply().hold()`

**Comment by quixotic-ambition** [comment]
@gilly3 could you please give an example for where you would call sendResponse in your above code? I can't seem to figure it out.
