### ISSUE TITLE
update changelog

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#2525]
more a reference issue, i'll give it a go but if anyone wants to try feel free ;)

**Comment by AdriVanHoudt** [comment]
Ok so somewhere there is a tag of 2.8 screwing up the changelog generation :neutral_face: 
This is as far as I got. Pinging @diffsky for help
Also I had to set `--remote hapijs/hapi` to make it work
```js
$ make changelog MDCHANGELOG_TOKEN=0ccd76d9778b184d6e7cd3cf305b7a61b711e204
[hapijs/hapi] fetching 1356/1356 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/joi] fetching 334/334 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/qs] fetching 48/48 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[moment/moment] fetching 712/712 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/shot] fetching 17/17 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/catbox] fetching 80/80 issues [====================] 100% 0.0s
[hapijs/shot] fetching 17/17 issues [====================] 100% 0.0s
[hapijs/joi] fetching 334/334 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/inert] fetching 16/16 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/wreck] fetching 41/41 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/hoek] fetching 98/98 issues [====================] 100% 0.0s
[hapijs/shot] fetching 17/17 issues [====================] 100% 0.0s
[hapijs/catbox] fetching 80/80 issues [====================] 100% 0.0s
[hapijs/shot] fetching 17/17 issues [====================] 100% 0.0s
[hapijs/joi] fetching 334/334 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/boom] fetching 35/35 issues [====================] 100% 0.0s
[hapijs/hoek] fetching 98/98 issues [====================] 100% 0.0s
[hapijs/catbox] fetching 80/80 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/call] fetching 8/8 issues [====================] 100% 0.0s
[hapijs/joi] fetching 334/334 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/mimos] fetching 9/9 issues [====================] 100% 0.0s
[hapijs/boom] fetching 35/35 issues [====================] 100% 0.0s
[hapijs/qs] fetching 48/48 issues [====================] 100% 0.0s
c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\node_modules\semver\semver.js:295
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: 2.8
    at new SemVer (c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\node_modules\semver\semver.js:295:11)
    at compare (c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\node_modules\semver\semver.js:571:10)
    at Function.gt (c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\node_modules\semver\semver.js:600:10)
    at c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\lib\formatter.js:27:20
    at Array.forEach (native)
    at findDependents (c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\lib\formatter.js:26:43)
    at formatIssue (c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\lib\formatter.js:41:3)
    at c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\lib\formatter.js:60:14
    at Array.forEach (native)
    at c:\Users\adri\AppData\Roaming\npm\node_modules\mdchangelog\lib\formatter.js:59:27
Makefile:8: recipe for target 'changelog' failed
make: *** [changelog] Error 1
```js

**Comment by diffsky** [comment]
A few things I noticed:
- it's worth updating the makefile to use the `--remote hapijs/hapi` option so that the command will work when run in someone's fork
- mdchangelog is refetching issues for repos that appear more than once as dependents (there are multiple `hapijs/joi` for example). This is a bug that I'll fix
- it looks like moment/moment is being parsed. That's probably not wanted as repos outside of the hapijs org might not follow strict semver (moment has the milestone that's `2.8` instead of `2.8.0`, see the [milestone list](https://github.com/moment/moment/milestones?state=closed)). I added some debug output and find this is the referencing issue: https://github.com/hapijs/hapi/issues/2454 - the issue text should be changed to not match the mdchangelog dependent repo style (compare to https://github.com/hapijs/hapi/issues/2227)

**Comment by AdriVanHoudt** [comment]
Yeah I added the remote to make it work, will add that in the PR as well, will that affect people generating from the original repo? 
I'll wait for the fix and @hueniverse or anyone else with edit rights on issues to fix the naming, although wouldn't it be better to only match org repos, like in this case only parse repos under hapijs/ or maybe also under a flag?

**Comment by diffsky** [comment]
restricting (via a flag) matching to org repos might be a good option to add, yeah.

**Comment by diffsky** [comment]
I've published an updated mdchangelog with the re-parsing bug and debug output
```
+ mdchangelog@0.6.0
```

I've exceeded my api use, so the flag restricting to the same org will have to wait... :D

**Comment by AdriVanHoudt** [comment]
yeah the rate limits make this very hard to test :D 
Also I ran it again with new version and now I get 

```js
$ make changelog MDCHANGELOG_TOKEN=0ccd76d9778b184d6e7cd3cf305b7a61b711e204
[hapijs/hapi] fetching 1356/1356 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/shot] fetching 17/17 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/joi] fetching 334/334 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/qs] fetching 48/48 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/wreck] fetching 41/41 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/catbox] fetching 80/80 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[moment/moment] fetching 712/712 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
{ [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git clone git@github.com:hapijs/hoek.git /tmp/mdchangelog-tdOxn6m/hapijs/hoek"
Cloning into '/tmp/mdchangelog-tdOxn6m/hapijs/hoek'...
Received disconnect from 192.30.252.130: 11: Bye Bye
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
]
  killed: false,
  code: 128,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "git clone git@github.com:hapijs/hoek.git /tmp/mdchangelog-tdOxn6m/hapijs/hoek"' }
Makefile:8: recipe for target 'changelog' failed
make: *** [changelog] Error 1

$ make changelog MDCHANGELOG_TOKEN=0ccd76d9778b184d6e7cd3cf305b7a61b711e204
[hapijs/hapi] fetching 1356/1356 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[hapijs/shot] fetching 17/17 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
[moment/moment] fetching 712/712 issues [====================] 100% 0.0s
Enter passphrase for key '/c/Users/adri/.ssh/id_rsa':
{ [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git clone git@github.com:hapijs/qs.git /tmp/mdchangelog-vK3daBy/hapijs/qs"
Cloning into '/tmp/mdchangelog-vK3daBy/hapijs/qs'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
]
  killed: false,
  code: 128,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "git clone git@github.com:hapijs/qs.git /tmp/mdchangelog-vK3daBy/hapijs/qs"' }
Makefile:8: recipe for target 'changelog' failed
make: *** [changelog] Error 1
```

**Comment by diffsky** [comment]
I think maybe github had some issues and your ssh connection got killed. Unrelated, I recommend you have a look into getting your passphrase stored by your OS so you don't have to keep entering it.

**Comment by AdriVanHoudt** [comment]
Could be and hmm yeah can windows do that?

**Comment by diffsky** [comment]
> can windows do that?

I'd hope there's some way. I don't have direct experience of that, maybe these will have an answer
- http://stackoverflow.com/questions/8518515/how-to-make-windows-remember-my-passphrase-key
- http://stackoverflow.com/questions/370030/why-git-cant-remember-my-passphrase-under-windows

**Comment by AdriVanHoudt** [comment]
Will take a look when I got time. So for now no changelog until the new
flag or only if I disable the flag to pull in other repos?

**Comment by diffsky** [comment]
I've just added a `--same-org` option and successfully generated the changelog: https://gist.github.com/diffsky/5858a813281bd19fd772

**Comment by AdriVanHoudt** [comment]
I was able to generate the changelog as well with the new flag, so :shipit: 
Thanks again @diffsky to help me fix this!
