### ISSUE TITLE
Deploy on heroku

### ISSUE THREAD

**Issue by paulomcnally** [hapijs/hapi#2528]
2015-05-11T05:08:19.977190+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/?from=88888888&to=87884734&message=%22Test%22" host=sheltered-reaches-2634.herokuapp.com request_id=c623cced-0242-44e4-9842-9da9325a3285 fwd="168.1.82.171" dyno= connect= service= status=503 bytes=
    2015-05-11T05:08:23.902797+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=sheltered-reaches-2634.herokuapp.com request_id=8f8596b4-79cc-4d14-89d7-645a03f01578 fwd="168.1.82.171" dyno= connect= service= status=503 bytes=
    2015-05-11T05:11:07.175285+00:00 heroku[web.1]: State changed from crashed to starting
    2015-05-11T05:11:07.102832+00:00 heroku[api]: Deploy f04a628 by paulomcnally@gmail.com
    2015-05-11T05:11:07.102832+00:00 heroku[api]: Release v4 created by paulomcnally@gmail.com
    2015-05-11T05:11:09.661242+00:00 heroku[web.1]: Starting process with command `node app.js`
    2015-05-11T05:11:11.675624+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    2015-05-11T05:11:11.675649+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
    2015-05-11T05:11:12.695881+00:00 app[web.1]: 
    2015-05-11T05:11:12.696925+00:00 app[web.1]:     throw new Error(msgs.join(' ') || 'Unknown error');
    2015-05-11T05:11:12.696988+00:00 app[web.1]:           ^
    2015-05-11T05:11:12.700442+00:00 app[web.1]:     at Object.exports.assert (/app/node_modules/hapi/node_modules/hoek/lib/index.js:678:11)
    2015-05-11T05:11:12.700444+00:00 app[web.1]:     at Object.module.exports.internals.Server (/app/node_modules/hapi/lib/server.js:30:10)
    2015-05-11T05:11:12.700439+00:00 app[web.1]: Error: Server must be instantiated using new
    2015-05-11T05:11:12.700447+00:00 app[web.1]:     at Module._compile (module.js:456:26)
    2015-05-11T05:11:12.700445+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:3:19)
    2015-05-11T05:11:12.700449+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
    2015-05-11T05:11:12.700450+00:00 app[web.1]:     at Module.load (module.js:356:32)
    2015-05-11T05:11:12.700452+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
    2015-05-11T05:11:12.700454+00:00 app[web.1]:     at Function.Module.runMain (module.js:497:10)
    2015-05-11T05:11:12.700455+00:00 app[web.1]:     at startup (node.js:119:16)
    2015-05-11T05:11:12.700457+00:00 app[web.1]:     at node.js:935:3
    2015-05-11T05:11:12.696484+00:00 app[web.1]: /app/node_modules/hapi/node_modules/hoek/lib/index.js:678
    2015-05-11T05:11:13.611554+00:00 heroku[web.1]: Process exited with status 8
    2015-05-11T05:11:13.625062+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by paulomcnally** [comment]
"hapi": "^8.4.0"

**Comment by Marsup** [comment]
The error is in the stack, it's unclear what you need help with.
