### ISSUE TITLE
server.decorate not working for "reply"

### ISSUE THREAD

**Issue by bboysathish** [hapijs/hapi#2560]
```
var hapi = require('hapi');
var server = new hapi.Server();

server.connection({ port: 3000 });

server.decorate('reply', 'success', function () {

    return this.response({ status: 'ok' });
});

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {

        return reply().success();
    }
});

server.start();

```

The above decorate function is not working.Showing this below error,

```
Debug: internal, implementation, error
    TypeError: Uncaught error: Object [object Object] has no method 'success'
    at server.route.handler (d:\E-Learning\nodejs\checkdecorate.js:16:24)
    at Object.internals.handler (d:\E-Learning\nodejs\node_modules\hapi\lib\hand
ler.js:94:36)
    at d:\E-Learning\nodejs\node_modules\hapi\lib\handler.js:28:23
    at internals.Protect.run (d:\E-Learning\nodejs\node_modules\hapi\lib\protect
.js:56:5)
    at exports.execute (d:\E-Learning\nodejs\node_modules\hapi\lib\handler.js:22
:22)
    at d:\E-Learning\nodejs\node_modules\hapi\lib\request.js:371:13
    at iterate (d:\E-Learning\nodejs\node_modules\hapi\node_modules\items\lib\in
dex.js:35:13)
    at done (d:\E-Learning\nodejs\node_modules\hapi\node_modules\items\lib\index
.js:27:25)
    at d:\E-Learning\nodejs\node_modules\hapi\node_modules\hoek\lib\index.js:841
:22
    at process._tickDomainCallback (node.js:486:13)
```

HAPIJS Version: 8.5.1
nodejs Version: 0.10.36

**Comment by gergoerdosi** [comment]
It should be called as `reply.success()`.

**Comment by bboysathish** [comment]
@gergoerdosi  Thank you.. my mistake.. just now i saw the tests too.
