### ISSUE TITLE
No method addroutes

### ISSUE THREAD

**Issue by jbarros35** [hapijs/hapi#2603]
Trying to add multiple routes as below
var Hapi = require('hapi');
var routes = require('./routes');

// Create a server with a host and port
var http = new Hapi.Server();
http.connection({ 
    host: 'localhost', 
    port: 8000 
});

// Add the route
http.addRoutes(routes);
// Start the server
http.start();

Error:

http.addRoutes(routes);
     ^
TypeError: Object [object Object] has no method 'addRoutes'
    at Object.<anonymous> (C:\Users\jlopesde\node\express\myapp\server.js:19:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by Marsup** [comment]
Where the hell did you see anything about addRoutes ? This is like years old, read up-to-date tutorials or documentation please.
