### ISSUE TITLE
Hapi erroring out on what looks to be an invalid dependency issue

### ISSUE THREAD

**Issue by toymachiner62** [hapijs/hapi#2643]
When i try to start my hapi server I see this error:

```sh
TypeError: Object [object Object] has no method 'items'
    at Object.<anonymous> (/var/www/myapp/current/hapi/node_modules/hapi/node_modules/vision/lib/manager.js:40:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/myapp/current/hapi/node_modules/hapi/node_modules/vision/lib/index.js:9:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Here's my package.json dependencies:
```js
...
"dependencies": {
    "bcrypt": "^0.8.0",
    "boom": "*",
    "config": "^1.12.0",
    "fullcontact": "^0.1.0",
    "gravatar": "^1.1.0",
    "hapi": "^8.0.0",
    "hapi-auth-basic": "^2.0.0",
    "hapi-authorization": "^2.1.2",
    "joi": "^6.0.3",
    "lodash": "^2.4.1",
    "mongo-factory": "0.0.5",
    "mongodb": "^1.4.19",
    "node-geocoder": "^2.12.1",
    "node-uuid": "^1.4.2",
    "nodemon": "^1.2.1",
    "q": "^1.1.2",
    "sendgrid": "^1.6.0",
    "underscore": "*"
  },
...
```

My hapi version is 8.8.0
```sh
$ npm list
myapp@0.0.0 /var/www/myapp/current/hapi
├─┬ bcrypt@0.8.3
│ ├── bindings@1.2.1
│ └── nan@1.8.4
├─┬ boom@2.8.0
│ └── hoek@2.14.0
├── config@1.14.0
├─┬ fullcontact@0.1.0
│ ├── qs@0.6.6
│ └─┬ request@2.21.0
│   ├── aws-sign@0.3.0
│   ├── cookie-jar@0.3.0
│   ├── forever-agent@0.5.2
│   ├─┬ form-data@0.0.8
│   │ ├── async@0.2.10
│   │ └─┬ combined-stream@0.0.7
│   │   └── delayed-stream@0.0.5
│   ├─┬ hawk@0.13.1
│   │ ├─┬ boom@0.4.2
│   │ │ └── hoek@0.9.1
│   │ ├── cryptiles@0.2.2
│   │ ├── hoek@0.8.5
│   │ └─┬ sntp@0.2.4
│   │   └── hoek@0.9.1
│   ├─┬ http-signature@0.9.11
│   │ ├── asn1@0.1.11
│   │ ├── assert-plus@0.1.2
│   │ └── ctype@0.5.2
│   ├── json-stringify-safe@4.0.0
│   ├── mime@1.2.11
│   ├── oauth-sign@0.3.0
│   └── tunnel-agent@0.3.0
├── gravatar@1.1.1
├─┬ hapi@8.8.0
│ ├── accept@1.0.0
│ ├── ammo@1.0.0
│ ├── boom@2.7.2
│ ├── call@2.0.1
│ ├── catbox@4.3.0
│ ├── catbox-memory@1.1.1
│ ├── cryptiles@2.0.4
│ ├─┬ h2o2@4.0.1
│ │ ├─┬ joi@5.1.0 invalid
│ │ │ ├── isemail@1.1.1
│ │ │ └── moment@2.10.2
│ │ └── wreck@5.6.1
│ ├─┬ heavy@3.0.0
│ │ └─┬ joi@5.1.0
│ │   ├── isemail@1.1.1
│ │   └── moment@2.10.3
│ ├── hoek@2.14.0
│ ├─┬ inert@2.1.5
│ │ └── lru-cache@2.6.4
│ ├── iron@2.1.2
│ ├── items@1.1.0
│ ├─┬ joi@6.4.1
│ │ ├── isemail@1.1.1
│ │ └── moment@2.10.3
│ ├── kilt@1.1.1
│ ├─┬ mimos@2.0.2
│ │ └── mime-db@1.14.0
│ ├── peekaboo@1.0.0
│ ├── qs@4.0.0
│ ├── shot@1.5.3
│ ├─┬ statehood@2.1.1
│ │ └─┬ joi@5.1.0 invalid
│ │   ├── isemail@1.1.1
│ │   └── moment@2.10.2
│ ├─┬ subtext@1.1.1
│ │ ├── content@1.0.1
│ │ └─┬ pez@1.0.0
│ │   ├── b64@2.0.0
│ │   └─┬ nigel@1.0.1
│ │     └── vise@1.0.0
│ ├── topo@1.0.2
│ ├─┬ vision@2.0.1
│ │ └─┬ joi@5.1.0 invalid
│ │   ├── isemail@1.1.1
│ │   └── moment@2.10.2
│ └── wreck@6.0.0
├─┬ hapi-auth-basic@2.0.0
│ └── hoek@2.14.0
├─┬ hapi-authorization@2.1.2
│ ├── hoek@2.14.0
│ └─┬ joi@5.1.0
│   ├── isemail@1.1.1
│   ├── moment@2.10.3
│   └── topo@1.0.2
├─┬ joi@6.5.0
│ ├── hoek@2.14.0
│ ├── isemail@1.1.1
│ ├── moment@2.10.3
│ └── topo@1.0.2
├─┬ lab@5.13.0
│ ├── bossy@1.0.3
│ ├── diff@1.4.0
│ ├─┬ eslint@0.24.1
│ │ ├─┬ chalk@1.1.0
│ │ │ ├── ansi-styles@2.1.0
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ ├── ansi-regex@2.0.0
│ │ │ │ └── get-stdin@4.0.1
│ │ │ ├─┬ strip-ansi@3.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ └── supports-color@2.0.0
│ │ ├─┬ concat-stream@1.5.0
│ │ │ ├── inherits@2.0.1
│ │ │ ├─┬ readable-stream@2.0.1
│ │ │ │ ├── core-util-is@1.0.1
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ ├── process-nextick-args@1.0.1
│ │ │ │ ├── string_decoder@0.10.31
│ │ │ │ └── util-deprecate@1.0.1
│ │ │ └── typedarray@0.0.6
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├─┬ doctrine@0.6.4
│ │ │ ├── esutils@1.1.6
│ │ │ └── isarray@0.0.1
│ │ ├── escape-string-regexp@1.0.3
│ │ ├─┬ escope@3.1.0
│ │ │ ├─┬ es6-map@0.1.1
│ │ │ │ ├── d@0.1.1
│ │ │ │ ├─┬ es5-ext@0.10.7
│ │ │ │ │ └── es6-symbol@2.0.1
│ │ │ │ ├─┬ es6-iterator@0.1.3
│ │ │ │ │ └── es6-symbol@2.0.1
│ │ │ │ ├── es6-set@0.1.1
│ │ │ │ ├── es6-symbol@0.1.1
│ │ │ │ └── event-emitter@0.3.3
│ │ │ ├─┬ es6-weak-map@0.1.4
│ │ │ │ ├── d@0.1.1
│ │ │ │ ├─┬ es5-ext@0.10.7
│ │ │ │ │ └── es6-symbol@2.0.1
│ │ │ │ ├─┬ es6-iterator@0.1.3
│ │ │ │ │ └── es6-symbol@2.0.1
│ │ │ │ └── es6-symbol@2.0.1
│ │ │ ├── esrecurse@3.1.1
│ │ │ ├── estraverse@3.1.0
│ │ │ └── util-extend@1.0.1
│ │ ├── espree@1.12.3 invalid
│ │ ├── estraverse@4.1.0
│ │ ├── estraverse-fb@1.3.1
│ │ ├── globals@8.2.0
│ │ ├─┬ inquirer@0.8.5
│ │ │ ├── ansi-regex@1.1.1
│ │ │ ├── cli-width@1.0.1
│ │ │ ├── figures@1.3.5
│ │ │ ├── lodash@3.10.0
│ │ │ ├─┬ readline2@0.1.1
│ │ │ │ ├── mute-stream@0.0.4
│ │ │ │ └── strip-ansi@2.0.1
│ │ │ ├── rx@2.5.3
│ │ │ └── through@2.3.8
│ │ ├─┬ is-my-json-valid@2.12.0
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ ├── jsonpointer@1.1.0
│ │ │ └── xtend@4.0.0
│ │ ├─┬ js-yaml@3.3.1
│ │ │ ├─┬ argparse@1.0.2
│ │ │ │ ├── lodash@3.10.0
│ │ │ │ └── sprintf-js@1.0.3
│ │ │ └── esprima@2.2.0
│ │ ├─┬ minimatch@2.0.8
│ │ │ └─┬ brace-expansion@1.1.0
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ ├── object-assign@2.1.1
│ │ ├─┬ optionator@0.5.0
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@1.0.6
│ │ │ ├── levn@0.2.5
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├── type-check@0.3.1
│ │ │ └── wordwrap@0.0.3
│ │ ├── path-is-absolute@1.0.0
│ │ ├── strip-json-comments@1.0.2
│ │ ├── text-table@0.2.0
│ │ ├── user-home@1.1.1
│ │ └── xml-escape@1.0.0
│ ├─┬ eslint-plugin-hapi@1.2.0
│ │ ├── hapi-capitalize-modules@1.1.0
│ │ ├── hapi-scope-start@1.1.1
│ │ └── no-shadow-relaxed@1.0.1
│ ├── espree@2.1.0
│ ├── esprima@1.2.5
│ ├─┬ handlebars@3.0.3
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├─┬ source-map@0.1.43
│ │ │ └── amdefine@1.0.0
│ │ └─┬ uglify-js@2.3.6
│ │   ├── async@0.2.10
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.3
│ │   └─┬ source-map@0.1.43
│ │     └── amdefine@0.1.0
│ ├── hoek@2.14.0
│ ├── items@1.1.0
│ ├─┬ jslint@0.9.1
│ │ ├── exit@0.1.2
│ │ ├─┬ glob@4.5.3
│ │ │ ├─┬ inflight@1.0.4
│ │ │ │ └── wrappy@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├─┬ minimatch@2.0.8
│ │ │ │ └─┬ brace-expansion@1.1.0
│ │ │ │   ├── balanced-match@0.2.0
│ │ │ │   └── concat-map@0.0.1
│ │ │ └─┬ once@1.3.2
│ │ │   └── wrappy@1.0.1
│ │ ├─┬ nopt@3.0.3
│ │ │ └── abbrev@1.0.7
│ │ └─┬ readable-stream@1.0.33
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └─┬ source-map-support@0.3.2
│   └─┬ source-map@0.1.32
│     └── amdefine@1.0.0
├── lodash@2.4.2
├── mongo-factory@0.0.5
├─┬ mongodb@1.4.38
│ ├─┬ bson@0.2.21
│ │ └── nan@1.7.0
│ ├─┬ kerberos@0.0.11
│ │ └── nan@1.8.4
│ └─┬ readable-stream@2.0.1
│   ├── core-util-is@1.0.1
│   ├── inherits@2.0.1
│   ├── isarray@0.0.1
│   ├── process-nextick-args@1.0.1
│   ├── string_decoder@0.10.31
│   └── util-deprecate@1.0.1
├─┬ node-geocoder@2.21.2
│ └─┬ commander@2.8.1
│   └── graceful-readlink@1.0.1
├── node-uuid@1.4.3
├─┬ nodemon@1.3.7
│ ├─┬ minimatch@0.3.0
│ │ ├── lru-cache@2.6.5
│ │ └── sigmund@1.0.1
│ ├─┬ ps-tree@0.0.3
│ │ └─┬ event-stream@0.5.3
│ │   └─┬ optimist@0.2.8
│ │     └── wordwrap@0.0.3
│ ├─┬ touch@0.0.3
│ │ └─┬ nopt@1.0.10
│ │   └── abbrev@1.0.7
│ └─┬ update-notifier@0.3.2
│   ├─┬ chalk@1.1.0
│   │ ├── ansi-styles@2.1.0
│   │ ├── escape-string-regexp@1.0.3
│   │ ├─┬ has-ansi@2.0.0
│   │ │ ├── ansi-regex@2.0.0
│   │ │ └── get-stdin@4.0.1
│   │ ├─┬ strip-ansi@3.0.0
│   │ │ └── ansi-regex@2.0.0
│   │ └── supports-color@2.0.0
│   ├─┬ configstore@0.3.2
│   │ ├── graceful-fs@3.0.8
│   │ ├─┬ js-yaml@3.3.1
│   │ │ ├─┬ argparse@1.0.2
│   │ │ │ ├── lodash@3.10.0
│   │ │ │ └── sprintf-js@1.0.3
│   │ │ └── esprima@2.2.0
│   │ ├─┬ mkdirp@0.5.1
│   │ │ └── minimist@0.0.8
│   │ ├── object-assign@2.1.1
│   │ ├─┬ osenv@0.1.3
│   │ │ ├── os-homedir@1.0.0
│   │ │ └── os-tmpdir@1.0.1
│   │ ├── user-home@1.1.1
│   │ ├── uuid@2.0.1
│   │ └── xdg-basedir@1.0.1
│   ├── is-npm@1.0.0
│   ├─┬ latest-version@1.0.1
│   │ └─┬ package-json@1.2.0
│   │   ├─┬ got@3.3.0
│   │   │ ├─┬ duplexify@3.4.2
│   │   │ │ ├─┬ end-of-stream@1.0.0
│   │   │ │ │ └─┬ once@1.3.2
│   │   │ │ │   └── wrappy@1.0.1
│   │   │ │ └─┬ readable-stream@2.0.1
│   │   │ │   ├── core-util-is@1.0.1
│   │   │ │   ├── inherits@2.0.1
│   │   │ │   ├── isarray@0.0.1
│   │   │ │   ├── process-nextick-args@1.0.1
│   │   │ │   ├── string_decoder@0.10.31
│   │   │ │   └── util-deprecate@1.0.1
│   │   │ ├── infinity-agent@2.0.3
│   │   │ ├── is-redirect@1.0.0
│   │   │ ├── is-stream@1.0.1
│   │   │ ├── lowercase-keys@1.0.0
│   │   │ ├── nested-error-stacks@1.0.0
│   │   │ ├── object-assign@2.1.1
│   │   │ ├── prepend-http@1.0.1
│   │   │ ├─┬ read-all-stream@2.2.0
│   │   │ │ └─┬ readable-stream@2.0.1
│   │   │ │   ├── core-util-is@1.0.1
│   │   │ │   ├── inherits@2.0.1
│   │   │ │   ├── isarray@0.0.1
│   │   │ │   ├── process-nextick-args@1.0.1
│   │   │ │   ├── string_decoder@0.10.31
│   │   │ │   └── util-deprecate@1.0.1
│   │   │ ├── statuses@1.2.1
│   │   │ └── timed-out@2.0.0
│   │   └─┬ registry-url@3.0.3
│   │     └─┬ rc@1.0.3
│   │       ├── deep-extend@0.2.11
│   │       ├── ini@1.3.4
│   │       ├── minimist@0.0.10
│   │       └── strip-json-comments@0.1.3
│   ├─┬ semver-diff@2.0.0
│   │ └── semver@4.3.6
│   └─┬ string-length@1.0.0
│     └─┬ strip-ansi@2.0.1
│       └── ansi-regex@1.1.1
├── q@1.4.1
├─┬ sendgrid@1.9.0
│ ├── mime@1.3.4
│ ├─┬ request@2.58.0
│ │ ├── aws-sign2@0.5.0
│ │ ├─┬ bl@0.9.4
│ │ │ └─┬ readable-stream@1.0.33
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── caseless@0.10.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@2.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@1.0.0-rc1
│ │ │ ├── async@1.3.0
│ │ │ └─┬ mime-types@2.1.2
│ │ │   └── mime-db@1.14.0
│ │ ├─┬ har-validator@1.8.0
│ │ │ ├── bluebird@2.9.33
│ │ │ ├─┬ chalk@1.1.0
│ │ │ │ ├── ansi-styles@2.1.0
│ │ │ │ ├── escape-string-regexp@1.0.3
│ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ ├── ansi-regex@2.0.0
│ │ │ │ │ └── get-stdin@4.0.1
│ │ │ │ ├─┬ strip-ansi@3.0.0
│ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├─┬ commander@2.8.1
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ └─┬ is-my-json-valid@2.12.0
│ │ │   ├── generate-function@2.0.0
│ │ │   ├─┬ generate-object-property@1.2.0
│ │ │   │ └── is-property@1.0.2
│ │ │   ├── jsonpointer@1.1.0
│ │ │   └── xtend@4.0.0
│ │ ├─┬ hawk@2.3.1
│ │ │ ├── cryptiles@2.0.4
│ │ │ ├── hoek@2.14.0
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@0.11.0
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.5
│ │ │ └── ctype@0.5.3
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.0.14
│ │ │ └── mime-db@1.12.0
│ │ ├── oauth-sign@0.8.0
│ │ ├── qs@3.1.0
│ │ ├── stringstream@0.0.4
│ │ ├─┬ tough-cookie@2.0.0
│ │ │ └── punycode@1.3.2
│ │ └── tunnel-agent@0.4.1
│ └── smtpapi@1.1.0
└── underscore@1.8.3

npm ERR! invalid: joi@5.1.0 /var/www/ava/current/hapi/node_modules/hapi/node_modules/h2o2/node_modules/joi
npm ERR! invalid: joi@5.1.0 /var/www/ava/current/hapi/node_modules/hapi/node_modules/statehood/node_modules/joi
npm ERR! invalid: joi@5.1.0 /var/www/ava/current/hapi/node_modules/hapi/node_modules/vision/node_modules/joi
npm ERR! invalid: espree@1.12.3 /var/www/ava/current/hapi/node_modules/lab/node_modules/eslint/node_modules/espree
npm ERR! not ok code 0
```

**Comment by gergoerdosi** [comment]
How does your view definition look like?

**Comment by AdriVanHoudt** [comment]
try removing `node_modules` and run `npm install` again if that doesn't work try clearing npm cache and reinstall

**Comment by Marsup** [comment]
What @AdriVanHoudt said, and it's also very bad practice to have dependencies as *.

**Comment by toymachiner62** [comment]
Seems an update of npm from version 1.4.26 to the latest version of 2.x did the trick.
