### ISSUE TITLE
npm install hapi misses wreck sub-dependency

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#2699]
When I run `npm install hapi@9.x` it does not install `wreck` even though it is a dependency of `subtext`. I suspect it is missing from the npm-shrinkwrap.json file.

**Comment by kanongil** [comment]
Note that this issue causes hapi 9.0.0 installs to be completely broken unless you manually `npm install wreck`, or already had it as a dependency.

```
> var Hapi = require('hapi');
Error: Cannot find module 'wreck'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/gil/test/node_modules/hapi/node_modules/subtext/lib/index.js:14:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by dave-irvine** [comment]
+1 Also getting this issue.

**Comment by bricss** [comment]
Same happed to me.

**Comment by devinivy** [comment]
PR #2701 seems to fix this for me.  Someone mind giving this a whirl other than me?  `npm install git://github.com/devinivy/hapi.git#9deps` should pull it in for you.

**Comment by AdriVanHoudt** [comment]
@hueniverse can you close the milestone if this is the only issue in the release (I assume yes since it is on npm) this way the changelog on hapijs.com catches it ;)
