### ISSUE TITLE
Registering Inert. Error: Handler name already exists

### ISSUE THREAD

**Issue by spiralni** [hapijs/hapi#2730]
I have a problem when registering Inert, it throws an error Handler name already exists

These are my config:
```
  "dependencies": {
    "actin": "0.0.1",
    "async": "^1.4.2",
    "bell": "^5.0.1",
    "blipp": "^2.2.1",
    "boom": "^2.8.0",
    "confidence": "^1.2.0",
    "glob": "^5.0.14",
    "glue": "^2.1.1",
    "good": "^6.3.0",
    "hapi": "^9.0.3",
    "hapi-auth-cookie": "^3.0.1",
    "hapi-swagger": "^1.1.0",
    "hoek": "^2.14.0",
    "inert": "^3.0.1",
    "joi": "^6.6.1",
    "lodash": "^3.10.1",
    "mongoose": "^4.1.3",
    "rejoice": "^2.0.1",
    "vision": "^3.0.0",
    "wreck": "^6.1.0"
  }
```
My full code is :

```javascript
var Hapi = require('hapi');
var Glue = require('glue');

var internals = {};
internals.manifest = {
    connections: [{
        host: 'localhost',
        port: 8000,
        labels: ['api']
    }],
    plugins: [
        { blipp: [{}] },
        { inert: [{ select: 'api', options: {} }]},
        { vision: [{}] },
        { 'hapi-swagger': [
            { 
                select: 'api' ,
                options: { apiVersion: 1.0 }
            }
        ]},
        { './models': [{ select: 'api', options: {} }] },
        { './controllers': [{ select: 'api', options: {} }] },
        { './routes': [{ select: 'api', options: {} }] }
    ]
};

Glue.compose(internals.manifest, { relativeTo: __dirname }, function (err, server) {

    if (err) {
        console.log('server.register err: ', err);
    }

    server.start(function() {
        console.log('server running at ', server.info.uri);
    });
});
```
Please your comments

**Comment by mtharrison** [comment]
Why is hapi not in your dependencies? What does `console.log(server.version)` show?

If it's < 9.0.0, then Inert was built in and you don't need to register it.

**Comment by spiralni** [comment]
Sorry, I just deleted the hapi entry because I downloaded it again. (updated now)

The problem is I want to use hapi-swagger, if I register it without inert or vision, the console says I need to register the dependencies, but if I include them, then it says "Handler name already exists"

This is the trace.
```
/home/spiralni/Documents/nodex/contacts-api/node_modules/hoek/lib/index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Handler name already exists: file
    at Object.exports.assert (/home/spiralni/Documents/nodex/contacts-api/node_modules/hoek/lib/index.js:723:11)
    at internals.Plugin.handler (/home/spiralni/Documents/nodex/contacts-api/node_modules/glue/node_modules/hapi/lib/plugin.js:359:10)
    at Object.exports.register (/home/spiralni/Documents/nodex/contacts-api/node_modules/inert/lib/index.js:23:12)
    at /home/spiralni/Documents/nodex/contacts-api/node_modules/glue/node_modules/hapi/lib/plugin.js:254:14
    at iterate (/home/spiralni/Documents/nodex/contacts-api/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/home/spiralni/Documents/nodex/contacts-api/node_modules/glue/node_modules/items/lib/index.js:38:9)
    at internals.Plugin.register (/home/spiralni/Documents/nodex/contacts-api/node_modules/glue/node_modules/hapi/lib/plugin.js:236:11)
    at /home/spiralni/Documents/nodex/contacts-api/node_modules/glue/lib/index.js:148:20
    at iterate (/home/spiralni/Documents/nodex/contacts-api/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at done (/home/spiralni/Documents/nodex/contacts-api/node_modules/glue/node_modules/items/lib/index.js:27:25)
```

**Comment by mtharrison** [comment]
Running same code and dependencies works fine for me (minus your models, controllers, routes plugin). I'm not sure what to suggest other than deleting your node modules directory and reinstalling dependencies from scratch.

**Comment by spiralni** [comment]
Hi, thanks.
It works now just as you said. 
Just deleted the node_modules directory and downloaded everything again.

Thanks a lot for your time!

**Comment by mtharrison** [comment]
:+1:  No worries.

**Comment by meg2208** [comment]
@mtharrison I am having the same issue, but I am using hapi 8.8.0 (< 9), so as you say I don't have to register it. How can I activate it properly in this case?

**Comment by mtharrison** [comment]
@meg2208 that version is over 2 years old! I would suggest you upgrade.
