### ISSUE TITLE
Hapi with http2 throws exception because `req.connection` is undefined

### ISSUE THREAD

**Issue by brillout** [hapijs/hapi#2745]
I'm trying to use Hapi with https://github.com/molnarg/node-http2 ;

```js
var path = require('path');
var fs = require('fs');
var http2 = require('http2');
var hapi = require('hapi');


var server = new hapi.Server();
server.connection({
    listener: http2.createServer({
        key: read('./cert/localhost.key'),
        cert: read('./cert/localhost.crt')
    }),
    tls: true,
    host: 'localhost',
    port: 8080
});

function read(relpath) {
    return fs.readFileSync(path.resolve(__dirname, relpath));
}

server.route({
    method: 'GET',
    path:'/',
    handler: function (request, reply) {
        reply('hello world');
    }
});

// Start the server
server.start(function() {
    console.log('Server running at:', server.info.uri);
});
```

but trying to perform a GET request results in following exception

```shell
Server running at: https://localhost:8080
/home/romu/tmp/hapi_test/node_modules/hapi/lib/request.js:113
        remoteAddress: req.connection.remoteAddress,
                                     ^
TypeError: Cannot read property 'remoteAddress' of undefined
    at new internals.Request (/home/romu/tmp/hapi_test/node_modules/hapi/lib/request.js:113:38)
    at internals.Generator.request (/home/romu/tmp/hapi_test/node_modules/hapi/lib/request.js:32:19)
    at Server.<anonymous> (/home/romu/tmp/hapi_test/node_modules/hapi/lib/connection.js:235:46)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at IncomingRequest.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at IncomingRequest.emit (events.js:166:7)
    at IncomingRequest._onHeaders (/home/romu/tmp/hapi_test/node_modules/http2/lib/http.js:634:8)
    at Stream.g (events.js:260:16)
```

**Comment by mtharrison** [comment]
I would suspect an issue with the http2 module. It has to provide a compatible `http` API for it to work with hapi. You might try filing an issue there.

FYI your example above works for me, when sending a request with curl:

`curl -k https://localhost:8080/`
