### ISSUE TITLE
More flaky tests?

### ISSUE THREAD

**Issue by ldesplat** [hapijs/hapi#2797]
Seems similar to https://github.com/hapijs/hapi/issues/2779

I am getting the following issues with node v4.1.1

```
Test script errors:

Multiple callbacks or thrown errors received in test "Request timeout does not return an error when server is responding when the timeout occurs" (error): Parse Error
      at Error (native)
      at Socket.socketOnData (_http_client.js:305:20)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:146:16)

There were 1 test script error(s).

Failed tests:

  428) Request timeout does not return an error when server is responding when the timeout occurs:

      Expected 39.175476014614105 to be at least 60

      at ClientRequest.<anonymous> (/Users/ldesplat/Projects/hapi/test/request.js:1457:54
```

**Comment by hueniverse** [comment]
I can't reproduce. The test looks fine now.
