### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jonahzheng** [hapijs/hapi#2925]
root@debian:~/hapi-example# node index.js

/root/hapi-example/node_modules/hapi/lib/index.js:5
const Server = require('./server');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/hapi-example/index.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

environment:
node 0.10.28
debain 6 amd64

**Comment by simon-p-r** [comment]
You need to upgrade node to version 4+

**Comment by Marsup** [comment]
You should have add many warnings on npm install, wasn't that the case ?

**Comment by jonahzheng** [comment]
think u，I don't notice warnings.
