### ISSUE TITLE
Getting error SyntaxError: Use of const in strict mode when using hapi.js version 8.8.0

### ISSUE THREAD

**Issue by arathim** [hapijs/hapi#2937]
When I start my nodejs server, I get this error in my log files

<mypath>/node_modules/glue/node_modules/hapi/lib/index.js:10
const internals = {};
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/nodejs/sg-admin/56422f6ec93894cc2998ca43/node_modules/glue/lib/index.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by gergoerdosi** [comment]
https://github.com/hapijs/hapi/issues/2925#issuecomment-153348748

**Comment by gergoerdosi** [comment]
Your hapi version is not 8.8.0.

**Comment by arathim** [comment]
How do i check what version of hapi.js is present?

**Comment by gergoerdosi** [comment]
If hapi is installed through glue, then check `/node_modules/glue/node_modules/hapi/package.json`.

**Comment by arathim** [comment]
I have hapi, 11.1.0. What should I do to fix this issue?

**Comment by simon-p-r** [comment]
What version of node are you using?

**Comment by gergoerdosi** [comment]
Hapi 11 requiest node v4 or later.

**Comment by arathim** [comment]
node --version
v0.10.33

**Comment by devinivy** [comment]
You'll have to upgrade to node v4 or downgrade to hapi v9.
