### ISSUE TITLE
Not possible to expose property in server.dependency()

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/hapi#2951]
I'm trying to expose a property in `server.dependency()` without luck.

```js
exports.register = function(server, options, done) {
  server.dependency('vision', (plugin, next) => {
    plugin.views({
        engines: {
          html: require('handlebars')
        },
        path: Path.join(__dirname, 'templates')
    });

    server.expose('test', () => {
      plugin.render('template', {}, (err, rendered) => {
        console.log(err);
      });
    });

    next();
  });

  done();
};
```

This code outputs:

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'test' of undefined
    at server.route.handler (/test/index.js:12:44)
    at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/test/node_modules/hapi/lib/handler.js:96:36)
    at /test/node_modules/hapi/lib/handler.js:30:23
    at internals.Protect.run.finish [as run] (/test/node_modules/hapi/lib/protect.js:64:5)
    at exports.execute.finalize (/test/node_modules/hapi/lib/handler.js:24:22)
    at each (/test/node_modules/hapi/lib/request.js:378:16)
    at iterate (/test/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/test/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.Auth.test.internals.Auth._setupRoute.internals.Auth._authenticate.authenticate [as _authenticate] (/test/node_modules/hapi/lib/auth.js:185:16)
    at internals.Auth.test.internals.Auth._setupRoute.internals.Auth.authenticate (/test/node_modules/hapi/lib/auth.js:177:17)
```

I tried to move `server.expose()` out of `server.dependency()`:

```js
exports.register = function(server, options, done) {
  server.dependency('vision', (plugin, next) => {
    plugin.views({
        engines: {
          html: require('handlebars')
        },
        path: Path.join(__dirname, 'templates')
    });

    next();
  });

  server.expose('test', () => {
    server.render('template', {}, (err, rendered) => {
      console.log(err);
    });
  });

  done();
};
```

But then I got:

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: server.render is not a function
    at Object.test (/test/custom-plugin.js:18:12)
    at server.route.handler (/test/index.js:12:45)
    at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/test/node_modules/hapi/lib/handler.js:96:36)
    at /test/node_modules/hapi/lib/handler.js:30:23
    at internals.Protect.run.finish [as run] (/test/node_modules/hapi/lib/protect.js:64:5)
    at exports.execute.finalize (/test/node_modules/hapi/lib/handler.js:24:22)
    at each (/test/node_modules/hapi/lib/request.js:378:16)
    at iterate (/test/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/test/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.Auth.test.internals.Auth._setupRoute.internals.Auth._authenticate.authenticate [as _authenticate] (/test/node_modules/hapi/lib/auth.js:185:16)
```

Is there a way to use `server.expose()` and `server.dependency()` at the same time?

**Comment by hueniverse** [comment]
I'm missing the code where you actually call the test method. Can you post a gist I can use to reproduce this?

**Comment by gergoerdosi** [comment]
Here is a test code: https://github.com/gergoerdosi/hapi-issue-2951

**Comment by hueniverse** [comment]
You never start or initialize your server so the after method is never called.

**Comment by gergoerdosi** [comment]
Thanks, got it working with `server.initialize()`.
