### ISSUE TITLE
Syntax Error when deploying on openshift

### ISSUE THREAD

**Issue by Dindaleon** [hapijs/hapi#2991]
Hi,
I get the following error when deploying hapi on opensihft: 

    /var/lib/openshift/5682c15989f5cfaf0c00017a/app-root/runtime/repo/node_modules/hapi/lib/index.js:5
    const Server = require('./server');
    ^^^^^
    SyntaxError: Use of const in strict mode.
        at Module._compile (module.js:439:25)
        at Module._extensions..js (module.js:474:10)
        at Object.require.extensions.(anonymous function) [as .js] (/var/lib/openshift/5682c15989f5cfaf0c00017a/app-root/runtime/repo/node_modules/babel-register/lib/node.js:138:7)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (server.js:202:2)
        at Module._compile (module.js:456:26)
        at loader (/var/lib/openshift/5682c15989f5cfaf0c00017a/app-root/runtime/repo/node_modules/babel-register/lib/node.js:130:5)
    DEBUG: Program node index.js exited with code 8
    DEBUG: Starting child process with 'node index.js'

I am using:
babel 6 with the following settings;

    require( 'babel-core/register' )({
      presets: ['es2015', 'stage-0', 'react'],
      plugins: [
        'transform-decorators-legacy'
      ]
    });

I have tried node versions 4.x and 5.x
npm version: 3.3.12
Hapi version: 11.0.0

**Comment by Marsup** [comment]
I doubt that's a node 4+. Check again.

**Comment by Dindaleon** [comment]
Currently using node 4.1.1

![oshapi](https://cloud.githubusercontent.com/assets/7036726/12079525/aa27eeb0-b20e-11e5-9795-38c9779b46d8.png)
![oshapi2](https://cloud.githubusercontent.com/assets/7036726/12079526/aa2a5f6a-b20e-11e5-8a5a-d9319b984437.png)

**Comment by Marsup** [comment]
Can you log what's in `process.versions` before requiring hapi ?

**Comment by Dindaleon** [comment]
I finally got it running! Yes, it was still running version 0.10 Now it's running node v5.x
