### ISSUE TITLE
server.select('non-existent-label') causes odd failures

### ISSUE THREAD

**Issue by antony** [hapijs/hapi#3021]
If I ```let conn = server.select('x')``` and x isn't a real label, if I then try to do something like ```conn.inject```, the error is:

```
  Error: Method not available when the selection has more than one connection or none
      at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
      at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin.inject (node_modules/hapi/lib/plugin.js:474:10)
      at Context.<anonymous> (test/xyz.test.js:28:17)
```

I would expect some validation around 'select'. Happy to fix this when I've got a spare moment.

**Comment by hueniverse** [comment]
It's your responsibility to check that the returned object has connections.
