### ISSUE TITLE
Error: Unknown handler: directory

### ISSUE THREAD

**Issue by dciccale** [hapijs/hapi#3056]
Just trying to serve static files but I get an error

`server.js`

```js
'use strict';

const Path = require('path');
const Hapi = require('hapi');

const server = new Hapi.Server();

server.connection({port: 9001});

server.route({
  method: 'GET',
  path: '/{param*}',
  handler: {
    directory: {
      path: 'public'
    }
  }
});

server.start((err) => {
  if (err) throw err;
  console.log('Server running at:', server.info.uri);
});
```

```sh
$ node server
/node_modules/hapi/node_modules/hoek/lib/index.js:732
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Unknown handler: directory
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
    at Object.exports.execute.internals.prerequisites.internals.handler.exports.defaults (/node_modules/hapi/lib/handler.js:108:14)
    at new module.exports.internals.Route.options (/node_modules/hapi/lib/route.js:55:37)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._addRoute (/node_modules/hapi/lib/connection.js:370:19)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._route (/node_modules/hapi/lib/connection.js:362:18)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin._apply (/node_modules/hapi/lib/plugin.js:575:14)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin.route (/node_modules/hapi/lib/plugin.js:545:10)
    at Object.<anonymous> (server.js:10:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by Marsup** [comment]
Have to add https://github.com/hapijs/inert.
