### ISSUE TITLE
Rejected promises in the context of "reply" get lost in the ether

### ISSUE THREAD

**Issue by pdufour** [hapijs/hapi#3135]
Hello, great framework! Been such a breeze to work with. One little quirk I noticed, if you `reply` with a Promise object, and it is rejected, the 500 error is shown, but that's it. I think it would be nice if the error was logged to stderr similar to how other errors are handled.

**Comment by mtharrison** [comment]
Rejected promises are logged for me. You probably just need to add `'error'` to your debug tags. Example:

```js
'use strict';

// Server

const Hapi = require('hapi');

const server = new Hapi.Server({
    debug: {
        request: ['error']  // log request errors
    }
});
server.connection({ port: 4000 });

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {

        const p = new Promise((resolve, reject) => {

            return setTimeout(() => reject(new Error('broken promise')), 500);
        });

        return reply(p);
    }
});

server.start((err) => {

    if (err) {
        throw err;
    }
    console.log('Started server');
});
```

Log on request:

```
Debug: handler, error
    {"msec":505.5404869914055,"error":"broken promise","data":{"isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
Debug: internal, error
    Error: broken promise
    at Timeout._onTimeout (/.../index.js:21:44)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by mtharrison** [comment]
Closing, please reopen if issue persists.
