### ISSUE TITLE
Npm shrinkwrap causing problems

### ISSUE THREAD

**Issue by jonathansamines** [hapijs/hapi#3151]
Hey, I´m just having a problem with the newer versions of hapi when trying to shrinkwrap my project dependencies. It looks like the current [hapi shrinkwrap](https://github.com/hapijs/hapi/blob/master/npm-shrinkwrap.json#L52) is not up-to-date, there are dependencies that are not included there.

For example if you look at the `package.json` of the current version of [mimos](https://github.com/hapijs/mimos/blob/v3.0.0/package.json#L16), you can see that depends both from mime-db and hoek, but the current hapi `shrinkwrap.json` only reflects the mime-db dependency.

The above results in a case when `hoek` is never installed, so when mimos look at that dependency load the hapi version of hoek. Under normal development circumstances that doesn´t cause any problem, in this case mimos (which requires the hoek#v3 end ups loading hoek#v4). But when that behaviour is resulting on a problem for us, is when I try to use shrinkwrap for my own dependencies. The above behaviour causes npm output the following: 

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jsamines/.nvm/versions/node/v4.4.3/bin/node',
1 verbose cli   '/Users/jsamines/.nvm/versions/node/v4.4.3/bin/npm',
1 verbose cli   'shrinkwrap' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/mimos requires hoek@'3.x.x' but will load
4 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/hoek,
4 warn unmet dependency which is version 4.0.0
5 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/subtext requires hoek@'3.x.x' but will load
5 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/hoek,
5 warn unmet dependency which is version 4.0.0
6 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/subtext/node_modules/pez requires hoek@'3.x.x' but will load
6 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/hoek,
6 warn unmet dependency which is version 4.0.0
7 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/subtext/node_modules/pez/node_modules/nigel requires hoek@'3.x.x' but will load
7 warn unmet dependency /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/hoek,
7 warn unmet dependency which is version 4.0.0
8 verbose stack Error: Problems were encountered
8 verbose stack Please correct and try again.
8 verbose stack invalid: hoek@4.0.0 /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/hoek
8 verbose stack     at shrinkwrap_ (/Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/lib/shrinkwrap.js:37:15)
8 verbose stack     at /Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/lib/shrinkwrap.js:31:5
8 verbose stack     at /Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/lib/ls.js:47:30
8 verbose stack     at /Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
8 verbose stack     at /Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
8 verbose stack     at cb (/Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
8 verbose stack     at /Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
8 verbose stack     at cb (/Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
8 verbose stack     at /Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
8 verbose stack     at cb (/Users/jsamines/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
9 verbose cwd /Users/jsamines/projects/my-webapp/server
10 error Darwin 14.5.0
11 error argv "/Users/jsamines/.nvm/versions/node/v4.4.3/bin/node" "/Users/jsamines/.nvm/versions/node/v4.4.3/bin/npm" "shrinkwrap"
12 error node v4.4.3
13 error npm  v2.15.1
14 error Problems were encountered
14 error Please correct and try again.
14 error invalid: hoek@4.0.0 /Users/jsamines/projects/my-webapp/server/node_modules/hapi/node_modules/hoek
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```
Do you know guys if that is an intended behaviour or actually a bug in hapi?

**Comment by PizzaBrandon** [comment]
I was running into the same thing just a moment ago with npm 2. I upgraded to npm 3, which resolves the packages differently, and shrinkwrap succeeded.

**Comment by jonathansamines** [comment]
The thing is that since I cannot upgrade my npm version right now to npm@3, mainly because of our current stack restrictions for deployment.

**Comment by Marsup** [comment]
You know you can update npm without node, right ?

**Comment by bjonica** [comment]
Why is this a non-issue? Does hapi not support npm@2?

**Comment by baldmountain** [comment]
We have this issue too. We pinned hapi to 13.3.x for now. When mimos and subtext are updated to use hoek 4.x we'll go back to using 13.x.
