### ISSUE TITLE
"path" is not allowed : Invalid routeConfig options (GET /employee/{id})

### ISSUE THREAD

**Issue by kumartarun** [hapijs/hapi#3239]
```

    "boom": "^2.10.1",
    "good": "^6.6.3",
    "good-console": "^5.1.0",
    "handlebars": "^4.0.3",
    "hapi": "^13.5.0",
    "hapi-cache-buster": "~0.4.0",
    "inert": "^3.2.1",
    "joi": "^2.9.0",
    "mongoose": "~3.8.7",
    "path": "^0.12.7",
    "vision": "^3.0.0"
```

```
(node) sys is deprecated. Use util instead.
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/home/nishant/hapi-examples/hapi-project/node_modules/hapi/node_modules/hoek/lib/index.js:737
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Invalid routeConfig options (GET /employee/{id}) {
  "cache": {
    "statuses": [
      200,
      204
    ],
    "otherwise": "no-cache"
  },
  "cors": false,
  "files": {
    "relativeTo": "."
  },
  "json": {
    "replacer": null,
    "space": null,
    "suffix": null
  },
  "payload": {
    "failAction": "error",
    "maxBytes": 1048576,
    "output": "data",
    "parse": true,
    "timeout": 10000,
    "uploads": "/tmp",
    "defaultContentType": "application/json"
  },
  "response": {
    "ranges": true,
    "emptyStatusCode": 200,
    "options": {}
  },
  "security": null,
  "state": {
    "parse": true,
    "failAction": "error"
  },
  "timeout": {
    "server": false
  },
  "validate": {
    "options": {},
    "path" [1]: {
      "id": {
        "_type": "string",
        "_settings": null,
        "_tests": [
          {
```
            "func": function (value, state, options) {\n\n        if (typeof value === 'string' ||\n            value === null ||\n            value === undefined) {\n\n            return null;\n        }\n\n        return Errors.create('string.base', null, state, options);\n    }
          },
          {
            "func": function (value, state, options) {\n\n        if (typeof value === 'string' &&\n            value.match(/^[a-zA-Z0-9]+$/)) {\n\n            return null;\n        }\n\n        return Errors.create('string.alphanum', null, state, options);\n    },
            "name": "alphanum"
          },
          {
            "func": function (value, state, options) {\n\n        if (typeof value === 'string' &&\n            value.length >= limit) {\n\n            return null;\n        }\n\n        return Errors.create('string.min', { value: limit }, state, options);\n    },
            "name": "min",
            "arg": 5
          }
        ],
        "_dependencies": [],
        "_mutators": [],
        "_valids": {
          "_set": {},
          "_lowercase": {}
        },
        "_invalids": {
          "_set": {
            "null": null,
            "''": ""
          },
          "_lowercase": {
            "null": null,
            "''": ""
          }
        },
        "_flags": {
          "insensitive": false,
          "allowOnly": false
        },
        "_description": null,
        "_notes": [],
        "_tags": []
      }
    }
  },
  "ext": {},
  "handler": function (request, reply) {\n            employeeObj.findById(request.params.id, function (err, employee) {\n                if (!err && employee) {\n                    reply(employee);\n                } else if (err) {\n                    // Log it, but don't show the user, don't want to expose ourselves (think security)\n                    console.log(err);\n                    reply(Boom.notFound());\n                } else {\n\n                    reply(Boom.notFound());\n                }\n            });\n        }
}

[1] "path" is not allowed
    at Object.exports.unique.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/node_modules/hoek/lib/index.js:737:11)
    at Object.exports.apply (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/schema.js:17:10)
    at new module.exports.internals.Route.options (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/route.js:59:28)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._addRoute (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/connection.js:387:19)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._route (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/connection.js:379:18)
    at module.exports.internals.Plugin.parent.auth.internals.Plugin.register.internals.Plugin._apply (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/plugin.js:572:14)
    at module.exports.internals.Plugin.parent.auth.internals.Plugin.register.internals.Plugin.route (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/plugin.js:542:10)
    at Object.exports.register (/home/nishant/hapi-examples/hapi-project/modules/user-management/groups/index.js:13:12)
    at Object.target [as register] (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Object.exports.register (/home/nishant/hapi-examples/hapi-project/modules/user-management/users/index.js:33:2)
    at Object.target [as register] (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/home/nishant/hapi-examples/hapi-project/node_modules/hapi/node_modules/items/lib/index.js:36:13)

**Comment by Marsup** [comment]
Highlighted in red in your console, read the error message.

**Comment by devinivy** [comment]
It's possible you meant to use `params` rather than `path` in your validation config.
