### ISSUE TITLE
    TypeError: reply(...).code is not a function  reply(err).code(400); is this not a method now ??

### ISSUE THREAD

**Issue by tkssharma** [hapijs/hapi#3241]
```
 "hapi": "^8.1.0",

 findById: function(request, reply){
    var id = request.params.id;

    Project.findById(id).exec(function(err, project){
      if(err){
        return reply(err).code(400);
      } else if(!project){
        return reply('project Not Found').code(404);
      } else {
        var projectObj = project.toObject();
        return reply(projectObj).code(200);
      }
    });
  }
```
```
Debug: internal, implementation, error 
    TypeError: reply(...).code is not a function
    at /home/nishant/swagger/REsourcify/controllers/companyCtrl.js:88:27
    at /home/nishant/swagger/REsourcify/node_modules/mongoose/lib/query.js:2217:21
    at /home/nishant/swagger/REsourcify/node_modules/kareem/index.js:207:48
    at /home/nishant/swagger/REsourcify/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
160725/095709.211, [response], http://nishant-Latitude-3450:8080: delete 
```/api/v1.1/company/1660899660809013 {} 500 (13ms)

**Comment by mtharrison** [comment]
`reply(err).code(400);` is probably the issue. [From `reply()` docs](http://hapijs.com/api#replyerr-result):

> If the input is not an Error object, the method returns a response object which provides a set of methods to customize the response (e.g. HTTP status code, custom headers, etc.). If the input is an Error object, the method returns back the error wrapped in a Boom object.

If you want to send 400 you can do `reply(Boom.badRequest())`.

**Comment by mtharrison** [comment]
Also your hapi version is extremely out of date. We're on version 13.5.0 now, I would advise upgrading.

**Comment by tkssharma** [comment]
You guys  not maintaining the change log .. if upgrade or downgrade lot of things need to change in big code base like ..
error coming after moving to 13.x 
```
TypeError: server.views is not a function when i move to 13.x version ...
    at Object.exports.register (/home/nishant/swagger/REsourcify/node_modules/hapi-swagger/lib/index.js:69:16)
    at Object.target [as register] (/home/nishant/swagger/REsourcify/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/home/nishant/swagger/REsourcify/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/home/nishant/swagger/REsourcify/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/nishant/swagger/REsourcify/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Plugin.parent.auth.internals.Plugin.register.each [as register] (/home/nishant/swagger/REsourcify/node_modules/hapi/lib/plugin.js:320:11)

```

**Comment by mtharrison** [comment]
The changelog needs no maintenance, it's automatically built from GitHub milestones. The steps to upgrade (including fixing your error above) are clearly documented in each release's release notes, if you look.
