### ISSUE TITLE
Boom.wrap never sends custom message to client

### ISSUE THREAD

**Issue by paulodiovani** [hapijs/hapi#3432]
#### Are you sure this is an issue with hapi or are you just looking for some help?

Yes. It's an API issue and related to #116.

I'm considering that:

1. For 4xx Errors, the `message` argument is always sent in the response for the client
2. For 5xx Errors, the `message` is hidden, sending always _"An internal server error occurred"_ to client response
3. `Boom.wrap` decorates an standard error with an optional `statusCode` (default to `500`) and `message`.

#### What are you trying to achieve or the steps to reproduce?

I'm trying to wrap standard errors to send to client, being ale to define the correct statusCode and message.

I'm using `wrap` instead of other Boom methods because I still have to log the original error message.

#### What was the result you received?

Wrapping errors as `5xx` errors works as expected as follows.

```javascript
> Boom.wrap(new Error('Original msg'), 500, 'Custom message')
{ Error: Custom message: Original msg
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:503:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function] }
```

However, wrapping an error as a `4xx` error sends the original error message to user and the custom message is only (able to be) logged.

```javascript
> Boom.wrap(new Error('Original msg'), 422, 'Custom message')
{ Error: Custom message: Original msg
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:503:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
  isBoom: true,
  isServer: false,
  data: null,
  output:
   { statusCode: 422,
     payload:
      { statusCode: 422,
        error: 'Unprocessable Entity',
        message: 'Original msg' },
     headers: {} },
  reformat: [Function] }
```

#### What did you expect?

- If `statusCode` is `5xx`, the message is hidden from the client. :white_check_mark: 
- If the `statusCode` is a `4xx` error, the error message is sent to the user. :white_check_mark: 
- If a _custom message_ is provided, the custom message is sent to the user and original is hidden. :x: 

I don't see any use of the `message` argument of `Boom.wrap` if it isn't to send a custom message to the client for `4xx` errors while hiding the original message.

#### Context

Tested with 

- boom@3.2.2
- boom@4.1.0

**Comment by paulodiovani** [comment]
Wrong repository.
Boom issue on https://github.com/hapijs/boom/issues/142
