### ISSUE TITLE
throw error when route contains dash

### ISSUE THREAD

**Issue by futurist** [hapijs/hapi#3452]
#### Are you sure this is an issue with hapi or are you just looking for some help?

It's a Issue

#### What are you trying to achieve or the steps to reproduce?

```js
server.route({
path: '/{json-api*}', ...
})
```

#### What was the result you received?

```
Error: Invalid path: /{json-api*}
    at Object.exports.assert (/Users/pro/projects/texman/server/node_modules/.4.1.0@hoek/lib/index.js:736:11)
    at exports.Router.internals.Router.internals.Router.analyze (/Users/pro/projects/texman/server/node_modules/.4.0.0@call/lib/index.js:181:10)
    at new module.exports.internals.Route (/Users/pro/projects/texman/server/node_modules/.16.1.0@hapi/lib/route.js:84:46)
    at module.exports.internals.Connection.internals.Connection._addRoute (/Users/pro/projects/texman/server/node_modules/.16.1.0@hapi/lib/connection.js:411:19)
    at module.exports.internals.Connection.internals.Connection._route (/Users/pro/projects/texman/server/node_modules/.16.1.0@hapi/lib/connection.js:403:18)
    at module.exports.internals.Server.internals.Plugin._apply (/Users/pro/projects/texman/server/node_modules/.16.1.0@hapi/lib/plugin.js:588:14)
    at module.exports.internals.Server.internals.Plugin.route (/Users/pro/projects/texman/server/node_modules/.16.1.0@hapi/lib/plugin.js:558:10)
    at Object.<anonymous> (/Users/pro/projects/texman/server/index.js:35:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

#### What did you expect?

Should allow dash in route name, or add document section for the rule of naming.

#### Context

* *node version*: 7.7.1
* *hapi version*: 16.0.0
* *os*: macOS 12
* *any other relevant information*:

**Comment by devinivy** [comment]
I believe route parameters may be named with "word characters."  In regex terms that's `\w` or `[A-Za-z0-9_]`.  Feel free to make a PR to the docs!

**Comment by Marsup** [comment]
Those parameters are converted to properties, I think it's intentional to avoid bracket accessors. I'd rather document it than "fix" it.

**Comment by hueniverse** [comment]
I'll take a documentation PR.
