### ISSUE TITLE
server.stop causes "socket hang up" error

### ISSUE THREAD

**Issue by roytz** [hapijs/hapi#3463]
#### Are you sure this is an issue with hapi or are you just looking for some help?
99% sure this is an issue with hapi

#### What are you trying to achieve or the steps to reproduce?
I'm using mocha for some tests on my hapi server.
I used the "after" function in order to stop the server (and make sure it stops) after finishing a set of tests.

```js
after((done) => {
    server.stop().then((err) => {
      if (err) { done(err) }
      done()
    })
      .catch((err) => done(err))
  })
```

#### What was the result you received?
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) code: 'ECONNRESET', response: undefined 

#### What did you expect?
The hapi server to stop without any problem.

#### Context

* *node version*: 7.7.2
* *hapi version*: master
* *os*: Mac OS Sierra
* *any other relevant information*:

**Comment by roytz** [comment]
My bad. Got it right now

**Comment by zaksmok** [comment]
What was the issue? I have the same problem
