### ISSUE TITLE
Tests fail on node 8

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#3508]
#### What was the result you received?

```
> hapi@16.3.0 test /Users/adri/Projects/hapitest/hapi-16.3.0
> lab -a code -t 100 -L -m 3000



  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  .................x................................
  .....................Debug: internal, implementation, error
    Error: not called
    at module.exports.internals.Response.request.response._marshal (/Users/adri/Projects/hapitest/hapi-16.3.0/test/transmit.js:1589:31)
    at internals.state (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/transmit.js:78:106)
    at Items.parallel (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/transmit.js:468:109)
    at Object.exports.parallel (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/items/lib/index.js:47:9)
    at Object.internals.state (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/transmit.js:461:100)
    at Object.internals.marshal (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/transmit.js:58:103)
    at Object.exports.send (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/transmit.js:29:103)
    at transmit (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/request.js:463:113)
    at Hoek.once (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/protect.js:49:103)
    at wrapped (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/hoek/lib/index.js:871:20)
    at done (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/items/lib/index.js:31:25)
    at finalize (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/request.js:414:112)
    at Function.wrapped [as _next] (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/hoek/lib/index.js:871:20)
    at Function.internals.continue (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/reply.js:139:96)
    at bound (domain.js:303:14)
    at Function.runBound [as continue] (domain.js:314:12)
    at preResponse (/Users/adri/Projects/hapitest/hapi-16.3.0/test/transmit.js:1592:42)
    at each (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/request.js:420:110)
    at iterate (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/items/lib/index.js:39:9)
    at _protect.run (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/request.js:423:103)
    at module.exports.internals.Protect.internals.Protect.run (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/protect.js:59:99)
    at internals.Request._invoke (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/request.js:403:125)
    at internals.Request._reply (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/request.js:470:105)
    at Items.serial (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/request.js:397:252)
    at done (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/items/lib/index.js:31:25)
    at finalize (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/handler.js:21:103)
    at Hoek.once (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/protect.js:49:103)
    at wrapped (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/hoek/lib/index.js:871:20)
    at finalize (/Users/adri/Projects/hapitest/hapi-16.3.0/lib/handler.js:89:103)
    at wrapped (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/hoek/lib/index.js:871:20)
    at Etag.apply (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/inert/lib/file.js:141:20)
    at applyEtag (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/inert/lib/etag.js:113:16)
    at Object.internals.computeHashed (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/inert/lib/etag.js:34:16)
    at Object.exports.apply (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/inert/lib/etag.js:120:22)
    at file.openStat (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/inert/lib/file.js:134:14)
    at Fs.fstat (/Users/adri/Projects/hapitest/hapi-16.3.0/node_modules/inert/lib/fs.js:72:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
x.....Debug: internal, implementation, error
    Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:227:30)
    at Readable.push (_stream_readable.js:195:10)
    at Timeout.setTimeout [as _onTimeout] (/Users/adri/Projects/hapitest/hapi-16.3.0/test/transmit.js:1800:34)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
..x....................
  ..................................................
  ...............................................

Failed tests:

  718) transmission marshal() closes file handlers when not reading file stream:

      actual expected

      200304

      Expected 200 to equal specified value

      at server.inject (/Users/adri/Projects/hapitest/hapi-16.3.0/test/transmit.js:96:48

  772) transmission transmit() does not open file stream on 304:

      Timed out (3000ms) - transmission transmit() does not open file stream on 304


  780) transmission transmit() does not leak stream data when request aborts before stream is returned:

      Timed out (3000ms) - transmission transmit() does not leak stream data when request aborts before stream is returned



3 of 897 tests failed
Test duration: 14058 ms
Assertions count: 2238 (verbosity: 2.49)
No global variable leaks detected
Coverage: 99.98% (1/4225)
lib/response.js missing coverage on line(s): 633
Code coverage below threshold: 99.98 < 100
Linting results: No issues
```
or see failing build https://travis-ci.org/hapijs/hapi/builds

#### What did you expect?

tests pass on node 8

#### Context

* *node version*: 8
* *hapi version*: 16.3.0
* *os*: Mac locally and linux on CI
* *any other relevant information*: looking at https://travis-ci.org/hapijs/hapi/builds it seems like https://github.com/hapijs/hapi/commit/241d7b0a0144539ac246725f3c9b8b0dbb88757d started to break the tests

(not sure if I should label this with test)

**Comment by devinivy** [comment]
Have you checked-out #3507 yet?

**Comment by AdriVanHoudt** [comment]
ok totally my bad!
