### ISSUE TITLE
Setting Response.code(X) in router with x<100 results in error with misleading stack trace

### ISSUE THREAD

**Issue by voukka** [hapijs/hapi#3566]
#### In my tests I used nonsense http codes like 1 and had a difficult time to understand what is not working in my router.

Example of failing router body: (`"hapi": "^16.4.3", "hapi-async-handler": "^1.0.3"`)
```js
{
        method: 'GET',
        path: '/wow',
        handler: {
            async: async function (request: Hapi.Request, reply: Hapi.ReplyNoContinue) {
                return reply('wow').code(1)
            }
        }
    }
```

#### What was the result you received?
```yarn jest v0.27.5
$ "some_path_to_module/node_modules/.bin/jest" "MeRoute.test.ts"
debug: Registered hapi-async-handler
debug: Registered Inert
debug: Registered hapi-router
debug: Registered ReverseProxyPlugin
debug: Registered CSRFValidationPlugin

 RUNS  server/routes/__tests__/MeRoute.test.ts
some_path_to_module/node_modules/hoek/lib/index.js:736
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Cannot wrap non-Error object
    at Object.<anonymous>.exports.assert (some_path_to_module/node_modules/hoek/lib/index.js:736:11)
    at Object.<anonymous>.exports.wrap (some_path_to_module/node_modules/boom/lib/index.js:75:10)
    at Object.<anonymous>.internals.writeHead (some_path_to_module/node_modules/hapi/lib/transmit.js:342:21)
    at Object.<anonymous>.internals.transmit (some_path_to_module/node_modules/hapi/lib/transmit.js:234:29)
    at internals.marshal (some_path_to_module/node_modules/hapi/lib/transmit.js:36:26)
    at Function.Object.<anonymous>.internals.Auth.response (some_path_to_module/node_modules/hapi/lib/auth.js:279:16)
    at response._marshal (some_path_to_module/node_modules/hapi/lib/transmit.js:105:25)
    at Object.<anonymous>.module.exports.internals.Response.Object.<anonymous>.internals.Response._streamify (some_path_to_module/node_modules/hapi/lib/response.js:606:12)
    at Object.<anonymous>.module.exports.internals.Response.Object.<anonymous>.internals.Response._marshal (some_path_to_module/node_modules/hapi/lib/response.js:547:21)
    at internals.state (some_path_to_module/node_modules/hapi/lib/transmit.js:79:18)
    at request.connection.states.format (some_path_to_module/node_modules/hapi/lib/transmit.js:507:20)
    at Items.serial (some_path_to_module/node_modules/statehood/lib/index.js:436:16)
    at done (some_path_to_module/node_modules/items/lib/index.js:31:25)
    at exports.prepareValue (some_path_to_module/node_modules/statehood/lib/index.js:431:20)
    at internals.sign (some_path_to_module/node_modules/statehood/lib/index.js:461:20)
    at process.nextTick (some_path_to_module/node_modules/hoek/lib/index.js:854:22)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
```

#### What did you expect?
To know that validation of HTTP code failed. 

*node version*: 8.2.1
*hapi version*: 16.4.3
*os*: Mac 10.12.6

**Comment by hueniverse** [comment]
This seems to be the result of using async handlers. Try again with v17 and let me know if this is still an issue.
