### ISSUE TITLE
escapeHtml fails

### ISSUE THREAD

**Issue by Diolor** [hapijs/hapi#3581]
#### What are you trying to achieve or the steps to reproduce?

Adding the following validation looks like it fails in Hapi. Joi.validate works as expected. I have the stacktrace below.

```js
validate: {
        payload: Joi.object({
            platform: Joi.string()
              .valid('ANDROID', 'IOS')
              .required(),
            title: Joi.string(),
            titleLocalizedKey: Joi.string()
          })
          .xor(
            'title',
            'titleLocalizedKey'
          )
      }
```

#### What was the result you received?

```
TypeError: input.charCodeAt is not a function
    at Object.exports.escapeHtml (/Users/d.lorentzos/Desktop/push/node_modules/hoek/lib/escape.js:42:32)
    at Object.exports.escapeHtml (/Users/d.lorentzos/Desktop/push/node_modules/hoek/lib/index.js:837:19)
    at postValidate (/Users/d.lorentzos/Desktop/push/node_modules/hapi/lib/validation.js:89:64)
    at internals.Object._validateWithOptions (/Users/d.lorentzos/Desktop/push/node_modules/joi/lib/types/any/index.js:660:20)
    at module.exports.internals.Any.root.validate (/Users/d.lorentzos/Desktop/push/node_modules/hapi/node_modules/joi/lib/index.js:121:23)
    at Object.internals.input (/Users/d.lorentzos/Desktop/push/node_modules/hapi/lib/validation.js:143:20)
    at exports.payload (/Users/d.lorentzos/Desktop/push/node_modules/hapi/lib/validation.js:44:22)
    at each (/Users/d.lorentzos/Desktop/push/node_modules/hapi/lib/request.js:413:16)
    at iterate (/Users/d.lorentzos/Desktop/push/node_modules/items/lib/index.js:36:13)

    at done (/Users/d.lorentzos/Desktop/push/node_modules/items/lib/index.js:28:25)
    at postValidate (/Users/d.lorentzos/Desktop/push/node_modules/hapi/lib/validation.js:70:20)
```

#### What did you expect?

No exception

#### Context

* *node version*: 8.5.0
* *hapi version*: 16.6.0
* *os*: mac os
* joi version: 11.0.1

**Comment by Marsup** [comment]
Joi 11 now produces arrays as paths, not sure how you want to proceed @hueniverse, should we make a 16.7 that supports both?

**Comment by hueniverse** [comment]
Sure, I'll take a hapi patch to deal with both.
