### ISSUE TITLE
SyntaxError in Hapi/lib/server.js

### ISSUE THREAD

**Issue by Janrupf** [hapijs/hapi#3695]
Hi, 
I'm trying to create a server with Hapi and TypeScript.
It is transpiling fine but when I try to run it it outputs the following error:

running with "node start.js"
```
/home/jannis/WebProjects/NodeJSServer/node_modules/hapi/lib/server.js:107
    decorate(type, property, method, options = {}) {
                                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jannis/WebProjects/NodeJSServer/node_modules/hapi/lib/index.js:5:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Running with "nodejs start.js"

```
/home/jannis/WebProjects/NodeJSServer/main/server.js:10
        this.hapiServer.connection({ port: this.port });
                        ^

TypeError: this.hapiServer.connection is not a function
    at Server.start (/home/jannis/WebProjects/NodeJSServer/main/server.js:10:25)
    at Object.<anonymous> (/home/jannis/WebProjects/NodeJSServer/start.js:5:8)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

Here is my TypeScript code:

server.ts:
```typescript
import * as Hapi from "hapi";
export class Server {

  private port: number;
  private hapiServer: Hapi.Server;

  constructor(port: number) {
    this.port = port;
    this.hapiServer = new Hapi.Server();
  }

  public start(): void {
    this.hapiServer.connection({port: this.port})
    this.hapiServer.start((err) => {
      if(err) {
        throw err;
      }

      console.log("Server running!");
    });
  }
}
```

start.ts:
```typescript
import * as PreparedServer from "./main/server";
let server: PreparedServer.Server = new PreparedServer.Server(7777);
server.start();
```

```
NodeJS: 9.2.0
OS: LinuxMint 18.2 64-bit
Hapi: 17.1.1
Typescript: 2.6.1
```

**Comment by bboysathish** [comment]
You are using wrong version.  Please use hapi@16

**Comment by Janrupf** [comment]
Thank you, downgrading fixed the issue!

**Comment by gubi** [comment]
I have this problem too!

**Comment by bboysathish** [comment]
@gubi  You are using wrong version. Please use hapi@16
