### ISSUE TITLE
payload authentication with v17.2.0

### ISSUE THREAD

**Issue by dnalborczyk** [hapijs/hapi#3736]
unless it's a bug, or wrong usage, there doesn't seem to be a proper way to exit payload authentication on failure.

hapi v17.2.0
node.js v9.5.0
macOS High Sierra 10.13.4 Beta (17E139j)

```javascript
export function scheme(server, options) {

  return {
    authenticate(request, h) {
      const { headers } = request;

      if (!headers.foo) {
        return h.unauthenticated(
          boom.badRequest('Missing header "foo" for authentication.')
        );
      }

      return h.unauthenticated();
    },

    payload(request, h) {
      const { payload } = request;

      // validate payload
      const isValid = verifyPayload(payload);

      if (!isValid) {
        return boom.unauthorized('Invalid payload');
      }

      return h.continue;
    }
}
```

you can ignore _authenticate()_ for this example.

for invalid cases the above code throws:
```
Debug: internal, implementation, error
        Error: Lifecycle methods called before the handler can only return an error, a takeover response, or a continue signal
        at Object.<anonymous>.module.exports.internals.Request._lifecycle (/foobar/node_modules/hapi/lib/request.js:285:40)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:160:7)
```

if we instead throw an Error:
```javascript
if (!isValid) {
    throw new Error('Invalid payload');
}
```

we get the following:
```
Debug: internal, implementation, error
        Error: Cannot throw non-error object
        at Object.<anonymous>.module.exports.internals.Manager.execute (/foobar/node_modules/hapi/lib/toolkit.js:42:33)
        at payload (/foobar/node_modules/hapi/lib/auth.js:370:54)
        at Object.<anonymous>.module.exports.internals.Request._lifecycle (/foobar/node_modules/hapi/lib/request.js:261:62)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:160:7)
```

response is in both cases the same:
```JSON
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}
```

the pre 17.x: handling was to use _reply_ with e.g. a _Boom_ object:
https://github.com/hapijs/hapi-auth-hawk/blob/master/lib/index.js#L78

```javascript
return reply(Boom.unauthorized('Payload is invalid'));
```

**Comment by hueniverse** [comment]
You should be able to return or throw an error object. I need a full example to look further.

**Comment by dnalborczyk** [comment]
thanks Eran! I'll spin up a repo to reproduce ...

**Comment by dnalborczyk** [comment]
_quick update:_ it really seems to be working as intended if used with hapi server.

the only difference I saw the above behavior with was using _hapi server.inject_ with [jest](https://github.com/facebook/jest).

I'll have a repro ready to be pushed in a bit if someone has the time for a quick look. it might as well be a jest bug.
