### ISSUE TITLE
redirecting in onRequest throws Cannot read property 'isOriginMatch' of null

### ISSUE THREAD

**Issue by jgallen23** [hapijs/hapi#3813]
We have a https redirect plugin that onRequest, if not https, then redirect to https (https://github.com/bendrucker/hapi-require-https).  As of 17.5.3, this causes the server to crash.  I pinned our server back to 17.5.2 and there was no issue.

Here is example stack trace
```
(node:24804) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isOriginMatch' of null
    at exports.headers (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/cors.js:171:28)
    at Object.internals.marshal (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/transmit.js:46:24)
    at Object.exports.send (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/transmit.js:31:25)
    at Request._reply (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/request.js:349:24)
    at <anonymous>
(node:24804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

more context: https://github.com/hapijs/discuss/issues/704

**Comment by mariecl** [comment]
I am also experiencing this issue.

In my case, one route handler calls the handler of another route under certain conditions. When those conditions are met, the "redirect" happens and I get the same `TypeError`.
