### ISSUE TITLE
Invalid schema content: (meta.$_root.alternatives)

### ISSUE THREAD

**Issue by terradek** [hapijs/hapi#3988]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.12.0
* *module version with issue*: 16.1.7
* *last module version without issue*: 15.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):FrisbyJS
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js
var metaOk = Joi.object({
    status: Joi.string().valid("ok"),
    error: null
}).options( convert: false, presence: "required");```


#### What was the result you got?

    assert(received)

    Expected value to be equal to:
      true
    Received:
      false
    
    Message:
      Invalid schema content: (meta.$_root.alternatives)

      at Object.<anonymous>.exports.schema (node_modules/joi/lib/cast.js:55:10)
      at Object.<anonymous>.internals.Object.keys (node_modules/joi/lib/types/object/index.js:359:35)
      at Object.<anonymous>.exports.schema (node_modules/joi/lib/cast.js:36:29)
      at Object.<anonymous>.internals.Object.keys (node_modules/joi/lib/types/object/index.js:359:35)
      at Object.<anonymous>.exports.schema (node_modules/joi/lib/cast.js:36:29)
      at Object.<anonymous>.internals.Object.keys (node_modules/joi/lib/types/object/index.js:359:35)
      at Object.<anonymous>.exports.schema (node_modules/joi/lib/cast.js:36:29)
      at Object.<anonymous>.module.exports.internals.Any.root.compile (node_modules/joi/lib/index.js:158:25)
      at Object.<anonymous>.module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:144:29)
      at jsonTypesAssertion (node_modules/frisby/src/frisby/expects.js:133:24)
```
#### What result did you expect?
Schema validation passed

**Comment by terradek** [comment]
Wrong product
