### ISSUE TITLE
Error: Method no longer accepts array arguments: items     at new module.exports (webpack:///./node_modules/@hapi/hoek/lib/error.js?:13:13)

### ISSUE THREAD

**Issue by raylyanway** [hapijs/hapi#3990]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v10.16.3
* *module version with issue*: "@hapi/hapi": "^18.4.0"
* *last module version without issue*: "hapi": "^18.1.0"
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:
```
"devDependencies": {
        "@babel/plugin-transform-runtime": "^7.4.0",
        "babel-eslint": "^10.0.3",
        "webpack": "^4.41.2",
        "webpack-cli": "^3.3.9",
        "webpack-dev-server": "^3.8.2",
        "webpack-manifest-plugin": "^2.2.0",
        "webpack-merge": "^4.2.2"
      ......
    },
    "dependencies": {
        "@babel/preset-env": "^7.3.4",
        "@babel/preset-react": "^7.0.0",
        "@hapi/boom": "^8.0.1",
        "@hapi/h2o2": "^8.3.2",
        "@hapi/hapi": "^18.4.0",
        "@hapi/inert": "^5.2.2"
        ......
    },
```

#### What are you trying to achieve or the steps to reproduce?

```js
import hapi from @hapi/hapi;
```

#### What was the result you got?

```
Error: Method no longer accepts array arguments: items
    at new module.exports (webpack:///./node_modules/@hapi/hoek/lib/error.js?:13:13)
    at module.exports (webpack:///./node_modules/@hapi/hoek/lib/assert.js?:16:9)
    at Object.exports.verifyFlat (webpack:///./node_modules/@hapi/joi/lib/common.js?:180:5)
    at internals.Base.method [as items] (webpack:///./node_modules/@hapi/joi/lib/types/array.js?:143:16)
    at eval (webpack:///./node_modules/@hapi/hapi/lib/config.js?:238:59)
    at Object../node_modules/@hapi/hapi/lib/config.js (/Users/user/work/retail-upsale-cards-ui/.build/server.js:610:1)
    at __webpack_require__ (/Users/user/work/retail-upsale-cards-ui/.build/server.js:21:30)
    at eval (webpack:///./node_modules/@hapi/hapi/lib/server.js?:11:16)
    at Object../node_modules/@hapi/hapi/lib/server.js (/Users/user/work/retail-upsale-cards-ui/.build/server.js:754:1)
    at __webpack_require__ (/Users/user/work/retail-upsale-cards-ui/.build/server.js:21:30)
Error: Method no longer accepts array arguments: items
    at new module.exports (webpack:///./node_modules/@hapi/hoek/lib/error.js?:13:13)
    at module.exports (webpack:///./node_modules/@hapi/hoek/lib/assert.js?:16:9)
    at Object.exports.verifyFlat (webpack:///./node_modules/@hapi/joi/lib/common.js?:180:5)
    at internals.Base.method [as items] (webpack:///./node_modules/@hapi/joi/lib/types/array.js?:143:16)
    at eval (webpack:///./node_modules/@hapi/hapi/lib/config.js?:238:59)
    at Object../node_modules/@hapi/hapi/lib/config.js (/Users/user/work/retail-upsale-cards-ui/.build/server.js:610:1)
    at __webpack_require__ (/Users/user/work/retail-upsale-cards-ui/.build/server.js:21:30)
    at eval (webpack:///./node_modules/@hapi/hapi/lib/server.js?:11:16)
    at Object../node_modules/@hapi/hapi/lib/server.js (/Users/user/work/retail-upsale-cards-ui/.build/server.js:754:1)
    at __webpack_require__ (/Users/user/work/retail-upsale-cards-ui/.build/server.js:21:30)
```

#### What result did you expect?

Correct work

**Comment by Marsup** [comment]
The stack trace says it all, what is your question?

**Comment by raylyanway** [comment]
Actually i don't understand how fix the error. I caught her and saw it may be a bug of hapi.

<img width="1672" alt="Screen Shot 2019-10-19 at 15 01 15" src="https://user-images.githubusercontent.com/35544150/67144659-9a9a0980-f281-11e9-8b82-299f6c25e9fe.png">
<img width="1591" alt="Screen Shot 2019-10-19 at 14 58 47" src="https://user-images.githubusercontent.com/35544150/67144660-9b32a000-f281-11e9-94b8-188c18dccc82.png">

**Comment by Marsup** [comment]
Items doesn't accept array arguments, pass individual arguments, or in this case spread the result of your concat.

**Comment by raylyanway** [comment]
This is the hapi code and not my application. I don't use the method items.

**Comment by raylyanway** [comment]
webpack:///./node_modules/@hapi/joi/lib/types/array.js?

**Comment by Marsup** [comment]
Oh, my bad. Then your npm install is wrong. I'd advise to reinstall them.

**Comment by hueniverse** [comment]
Must be some old npm modules cached.

**Comment by raylyanway** [comment]
Clean cache doesn't help. I can't use 
```js
import hapi from '@hapi/hapi';
```
without bugs. I should use  
```js
import hapi from 'hapi';
```
for correct work.

**Comment by Marsup** [comment]
You shouldn't drag old dependencies at the same time as the new ones, this can only lead to problems.
Can you show the result of `npm ls` ?

**Comment by raylyanway** [comment]
I don't use both hapi and @hapi/hapi at the same time. In my project only one package.
[npmlist-without-bug.txt](https://github.com/hapijs/hapi/files/3748009/npmlist.txt)
[npmlist-with-bug.txt](https://github.com/hapijs/hapi/files/3748011/npmlist-with-bug.txt)

**Comment by Marsup** [comment]
That's your package lock, not npm ls. Hapi clearly is getting joi@16 while it's declaring a joi@15 dependency. So either your install is wrong or webpack is.

**Comment by raylyanway** [comment]
I see that @hapi/hapi 18.4.0 has dependence from @hapi/joi 15.1.1 in my file. I'll try to figure out how it happened. Thanks.

**Comment by Marsup** [comment]
Are your node_modules bundled as well or left outside ? If yes, I'd look at that.

**Comment by raylyanway** [comment]
No, my node_modules inside project.
<img width="1364" alt="Screen Shot 2019-10-20 at 19 19 00" src="https://user-images.githubusercontent.com/35544150/67162647-94358b80-f36e-11e9-8ebf-9340e84a2cd7.png">

**Comment by raylyanway** [comment]
I tried to install the dependencies using yarn, but still the same error.

**Comment by Marsup** [comment]
Then I guess the bundle is bad. It's a bit of a hit or miss situation unless you can provide a repo where it's reproducable.

**Comment by raylyanway** [comment]
You're right. I'll think about it. Thanks.

**Comment by kamontat** [comment]
Here is reproduce repository: https://github.com/kamontat/KingKnight

**Comment by ChrisK1994** [comment]
Did you solve this problem?
