### ISSUE TITLE
Problem with serving static file

### ISSUE THREAD

**Issue by jk1z** [hapijs/hapi#4010]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 10.16.0
* *module version*: 18.3.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

Getting this error whenever I tried to serve the file locally.

```js
const response = h.file(pdfTmpPath, {
                    confine: false,
                    filename: pdfFileName,
                    mode: "attachment",
                    type: "application/pdf"
                });
                return response;

```
^ the `pdfTmpPath` is path to a pdf in a `tmp` directory
Error
```
[TypeError: response.source.file.close is not a function
  at Object.internals.close (/***/node_modules/@hapi/inert/lib/file.js:248:30)
  at module.exports.internals.Response._close (/***/node_modules/@hapi/hapi/lib/response.js:601:34)
  at Request._setResponse (/***/node_modules/@hapi/hapi/lib/request.js:458:27)
  at Object.exports.send (/***/node_modules/@hapi/hapi/lib/transmit.js:32:17)
  at process._tickCallback (internal/process/next_tick.js:68:7)
]
```

**Comment by hueniverse** [comment]
You need to open this issue in hapijs/inert.
