### ISSUE TITLE
GET ERROR WHEN FOLLOW THE GET START Tutorial Unexpected token =

### ISSUE THREAD

**Issue by ocyangel** [hapijs/hapi#4023]
#### Context

* *node version*:v10.16.2
* *module version*: hapi19.0.4

#### What are you trying to achieve or the steps to reproduce ?
Follow your get start Tutorial https://hapi.dev/tutorials/?lang=en_US

```js
'use strict';

const Hapi = require('@hapi/hapi');

const init = async () => {

    const server = Hapi.server({
        port: 3000,
        host: 'localhost'
    });

    await server.start();
    console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {

    console.log(err);
    process.exit(1);
});

init();
```
Get error as folow:
```js
$ node index
C:\Users\O-PC\Desktop\p\node_modules\@hapi\joi\lib\errors.js:246
    isJoi = true;
          ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)  
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\O-PC\Desktop\p\node_modules\@hapi\joi\lib\index.js:9:16)      
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by Marsup** [comment]
You need to use node 12 if you're going to use hapi 19. Note that hapi 19 has very recently been released, not all tutorials will fit perfectly. If you want to learn hapi I'd suggest you stick with hapi 18 until all educational materials are ready as it will be easier for you to follow along.

**Comment by ocyangel** [comment]
@Marsup thanks, it works for me
