### ISSUE TITLE
server.auth.strategy fails silently

### ISSUE THREAD

**Issue by DerMolly** [hapijs/hapi#4098]
#### Support plan

* *which support plan is this issue covered by?* Community
* *is this issue currently blocking your project?* no
* *is this issue affecting a production system?* no

#### Context

* *node version*: 12.16.3
* *module version with issue*: 19.1.1
* *last module version without issue*: don't know
* *environment*: node
* *used with*:  standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

When trying to configure `server.auth.strategy` (to use @hapi/basic) the option fail silently when provided with unexpected content e.g.

```
   server.auth.strategy('simple', 'basic', { validateBasic });
```
instead of
```
   server.auth.strategy('simple', 'basic', { validate: validateBasic });
```

#### What was the result you got?

```
/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js start
> backend@1.0.0 start <some_folder>
> ts-node --log-error src/index.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@1.0.0 start: `ts-node --log-error src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!    <log_file>
Process finished with exit code 1
```

the mentioned log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle backend@1.0.0~prestart: backend@1.0.0
6 info lifecycle backend@1.0.0~start: backend@1.0.0
7 verbose lifecycle backend@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle backend@1.0.0~start: PATH: <path>
9 verbose lifecycle backend@1.0.0~start: CWD: <project_folder>
10 silly lifecycle backend@1.0.0~start: Args: [ '-c', 'ts-node --log-error src/index.ts' ]
11 silly lifecycle backend@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle backend@1.0.0~start: Failed to exec start script
13 verbose stack Error: backend@1.0.0 start: `ts-node --log-error src/index.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid backend@1.0.0
15 verbose cwd <project_folder>
16 verbose Linux 5.3.0-51-generic
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error backend@1.0.0 start: `ts-node --log-error src/index.ts`
22 error Exit status 1
23 error Failed at the backend@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

#### What result did you expect?

Some kind of error message indicating what the problem was

**Comment by jonathansamines** [comment]
@DerMolly Can you put together a complete reproduction example to run in my local environment and debug? Just looking at your logs seems unlikely that the issue is caused by neither hapi or the basic plugin.

**Comment by DerMolly** [comment]
I tried to do that, but now everything works, very strange.
I'll close this issue as it seems not to be an hapi issue...
thanks for your effort
