### ISSUE TITLE
Problem updating to HAPI latest version / async

### ISSUE THREAD

**Issue by advapiIT** [hapijs/hapi#4205]
#### Support plan

* *is this issue currently blocking your project?* (yes):
* *is this issue affecting a production system?* (no):

#### Context

* *node version*: 13.1.0
* *module version*: 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):hapi latest version
* *any other relevant information*:

#### How can we help?

I'm trying to move to latest HAPI version but I've got issue with the following code. 

```js
Auth.replyWithToken = function (textok, results, reply) {
    //successlog.info('Creating token for session ID: ' + results.session_id);
    successlog.info('\tAuth.replyWithToken\Create token for session\t' + results.session_id + '\t\t');
    if (results.session_id) {
        var JWT = require('jsonwebtoken');
        var obj = { "sessionid": results.session_id, "username": results.username }; // object/info you want to sign 
        var token = JWT.sign(obj, Consts.authKey);
        var cookie_options = {
            ttl: 365 * 24 * 60 * 60 * 1000, // expires a year from today 
            encoding: 'none',    // we already used JWT to encode
            isSecure: false,      // warm & fuzzy feelings
            isHttpOnly: true,    // prevent client alteration
            clearInvalid: false, // remove invalid cookies
            isSameSite: false,
            strictHeader: true   // don't allow violations of RFC 6265
        };
        //reply({text: textok + ' ok'})
        results["token"] = token;
        reply(results)
            .header("Authorization", token)
            .state("token", token, cookie_options); //setto il cookie
    }
    else {
        return reply(Boom.unauthorized('Invalid login or password'));
    }
};

```

This code has been moved from this (old hapi version)

```
Auth.replyWithToken = function (textok, results, reply) {
    //successlog.info('Creating token for session ID: ' + results.session_id);
    successlog.info('\tAuth.replyWithToken\Create token for session\t' + results.session_id + '\t\t');
    if (results.session_id) {
        var JWT = require('jsonwebtoken');
        var obj = { "sessionid": results.session_id, "username": results.username }; // object/info you want to sign 
        var token = JWT.sign(obj, Consts.authKey);
        var cookie_options = {
            ttl: 365 * 24 * 60 * 60 * 1000, // expires a year from today 
            encoding: 'none',    // we already used JWT to encode
            isSecure: false,      // warm & fuzzy feelings
            isHttpOnly: true,    // prevent client alteration
            clearInvalid: false, // remove invalid cookies
            isSameSite: false,
            strictHeader: true   // don't allow violations of RFC 6265
        };
        //reply({text: textok + ' ok'})
        results["token"] = token;
        reply(results)
            .header("Authorization", token)
            .state("token", token, cookie_options); //setto il cookie
    }
    else {
        return reply(Boom.unauthorized('Invalid login or password'));
    }
}
```

The problem I've is that even if I got a successfull, I got a 500 error on nodejs... the error is

```
Debug: internal, implementation, error
    Error: handler method did not return a value, a promise, or throw an error
    at exports.Manager.execute (C:\Quadrivium\Node_wf\node_modules\@hapi\hapi\lib\toolkit.js:81:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.internals.handler (C:\Quadrivium\Node_wf\node_modules\@hapi\hapi\lib\handler.js:46:20)
    at async exports.execute (C:\Quadrivium\Node_wf\node_modules\@hapi\hapi\lib\handler.js:31:20)
    at async Request._lifecycle (C:\Quadrivium\Node_wf\node_modules\@hapi\hapi\lib\request.js:370:32)
    at async Request._execute (C:\Quadrivium\Node_wf\node_modules\@hapi\hapi\lib\request.js:279:9)
```

My Route is defined as

```
var routes = [
    {
        method: 'GET',
        path: '/server_is_up',
        config: { auth: false },
        handler: function(request, reply) { return true; }
    },
    {
        method: 'POST',
        path: '/login',
      //  config: { auth: false },

        handler:	async function (request, h) {
            try {
                 var credentials  = await auth.login_handler(request, h);
				 
				
            }
            catch (err) {
                console.log("->" + err);
                return { status: err.message };
            }
        },
		options: {
                 auth: {
                     mode: 'try'
                 }
             }
    }
```

What am I doing wrong? how do I change the reply(.....) so that it works?
Thanks in advance

**Comment by Nargonath** [comment]
It looks like you are not familiar with hapi's latest version API. I recommend you have a look at the tutorials on the website: https://hapi.dev/tutorials/?lang=en_US. Also Eran wrote a detailed release note when `hapi@17` came around: https://github.com/hapijs/hapi/issues/3658. I think you'll find a lot of useful information and probably the answer to your problem. This is the version where the breaking changes you're facing were first introduced.

If you still have trouble even after reading these resources you can come to our Slack channel where community members can provide you some help. You'll find a link to that slack from this page on our website: https://hapi.dev/support/.

Good luck. 👍

**Comment by Nargonath** [comment]
On a side note, the error you are seeing is because you don't return a value from your handler in your route configuration. You shouldn't use `reply` anymore to return values to your client but rather the response toolkit `h` that you get as the second argument of your handler.
