### ISSUE TITLE
inert + hapi may be leaking file descriptors

### ISSUE THREAD

**Issue by deej-split** [hapijs/hapi#4256]
#### Support plan

Free plan

* *is this issue currently blocking your project?* (yes/no):  no (actually, sorta... )
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 12.18.4
* *module version with issue*: inert@6.0.3
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): @hapi/hapi@20.1.3
* *any other relevant information*: There may or may not be a conversation about this on the community slack channel: https://hapihour.slack.com/archives/C6CEEUE06/p1622675671016200

#### What are you trying to achieve or the steps to reproduce?

We are serving static files with Hapi and Inert, and we are using up all the file descriptors on the host system.

We are calling:
```js
      const response = h.file(filename, {
        confine: true,
        etagMethod: false,
      });
```

One day some of our microservices suddenly reported errors that the number of file descriptors on their systems were exhausted.

Some more exploration let me to check the number of file descriptors on the linux systems this was running on `ls /proc/${pid}/fd` and I saw these appeared to be incrementing by one for each file.  I then identified that this also happens on my development machine (a mac) using `lsof -p ${pid}`. From here, I began to debug and `console.log()` may way through inert, and gradually found that the `prepare()` routine in Inert's `file.js` is getting called twice on each request.  But only one of the file descriptors are being closed.  The two calls have these stack traces:

```
    at exports.File.open (/Users/demo/project/node_modules/@hapi/inert/lib/fs.js:35:22)
    at async exports.File.openStat (/Users/demo/project/node_modules/@hapi/inert/lib/fs.js:88:9)
    at async Object.internals.prepare (/Users/demo/project/node_modules/@hapi/inert/lib/file.js:111:22)
    at async exports.Manager.execute (/Users/demo/project/node_modules/@hapi/hapi/lib/toolkit.js:105:28)
    at async Object.internals.handler (/Users/demo/project/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/Users/demo/project/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at async Request._lifecycle (/Users/demo/project/node_modules/@hapi/hapi/lib/request.js:372:32)
    at async Request._execute (/Users/demo/project/node_modules/@hapi/hapi/lib/request.js:280:9)
```

```
    at exports.File.open (/Users/demo/project/node_modules/@hapi/inert/lib/fs.js:35:22)
    at async exports.File.openStat (/Users/demo/project/node_modules/@hapi/inert/lib/fs.js:88:9)
    at async Object.internals.prepare (/Users/demo/project/node_modules/@hapi/inert/lib/file.js:111:22)
    at async exports.Manager.execute (/Users/demo/project/node_modules/@hapi/hapi/lib/toolkit.js:105:28)
    at async Request._invoke (/Users/demo/project/node_modules/@hapi/hapi/lib/request.js:399:30)
    at async Request._postCycle (/Users/demo/project/node_modules/@hapi/hapi/lib/request.js:470:32)
    at async Request._reply (/Users/demo/project/node_modules/@hapi/hapi/lib/request.js:449:9)
```

What seems to be most relevant is that these are coming from line 280 and 281 in hapi's request.js

```
        await this._lifecycle();
        this._reply();
```

What is interesting is that the call coming from the `_reply()` line gets to `prepare()` in inert, and at that point it has the info in `response.source.file` which was set up by the call coming from the `_lifecycle()` call.  However, this call then overwrites that data with a new call to open().  This appears to be where the leak is happening.

It thus looks to me like adding this to `file.js` in inert (around line 99) would fix the problem.

```
    if (source.file) {
        return response;
    }
```

I am not an expert on the hapi codebase, though, and from the documentation on hapi.dev, it seems like it is expected that prepare() would be opening a file descriptor.  Thus, I do not know if this problem is with inert and hapi, or if there's some aspect of how we are using this that is bad.

I'm happy to do more work to try to identify the problem, and create a PR.  I'd love to get some knowledge knowledge to help me more quickly understand why these calls are happening (I haven't yet debugged deeply into these flows yet)

#### What was the result you got?

65535 file descriptors used over a period of time.

#### What result did you expect?

No leaking file descriptors.

**Comment by deej-split** [comment]
@kanongil Oh, it looks like this is already on the hapi project (somehow I'd misremembered that I'd filed it on inert).  I'll leave this here, I guess.  In any case, what you are saying sounds right.

**Comment by kanongil** [comment]
Don't worry, I moved it over from inert 😀

**Comment by deej-split** [comment]
!thanks @kanongil !

**Comment by kanongil** [comment]
Thank you for the thorough report and @devinivy for finding the trigger – and congrats of finding a rare hapi error 😉
