### ISSUE TITLE
Server crashes if a requested aborted during sending a response. 

### ISSUE THREAD

**Issue by mshustov** [hapijs/hapi#4294]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: v14.17.6
* *module version with issue*: v20.2.0
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): "@hapi/inert": "6.0.4"
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

I spent the whole day struggling with the flaky integration tests that were caused by unhandled promise rejection in Hapi sever when an incoming request is **aborted**.
The server crashes with 
```
│ proc [kibana] TypeError: Cannot read property 'on' of null
   │ proc [kibana]     at Object.internals.chain (@hapi/hapi/lib/transmit.js:365:18)
   │ proc [kibana]     at Object.internals.transmit (@hapi/hapi/lib/transmit.js:120:30)
   │ proc [kibana]     at Object.exports.send (@hapi/hapi/lib/transmit.js:28:25)
   │ proc [kibana]     at Request._reply (@hapi/hapi/lib/request.js:459:9)
```

What I learned from the code inspection so far:
- Hapi receives an incoming request and calls a route handler
- the route handler responds with a JSON object
- Hapi started sending a request, https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L28. Note that Hapi already checked the response in not failed! https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L22-L24
- the incoming request is aborted
- Hapi overrides the response with Boom error `Request aborted` https://github.com/hapijs/hapi/blob/master/lib/request.js#L728
- server starts transmitting the original response containing the JSON object
- server crashes. 

I guess it might happen because of a discrepancy between `response` and `response.request.response` content in `transmit` method https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L28
I worked around the problem locally by adding the next snippet at the very top of `transmit`.
```js
    if (response.request.response.isBoom) {
      await internals.fail(request, response.request.response);
      return;
    }
```
I don't think it's a proper fix but I don't know Hapi codebase to fix the problem on my own so I'd appreciate any hints from the maintainers before I can open a PR.

Might be related to https://github.com/hapijs/hapi/issues/4244#issuecomment-933634956 but the issue doesn't mention any problems with runtime errors.

#### What was the result you got?

Hapi crashes if an incoming request is aborted while the server is sending a response.

#### What result did you expect?
Hapi handles the `abort` event gracefully.

**Comment by devinivy** [comment]
Thanks for the report!  @kanongil I know you are looking at related areas of the codebase right now, so just wanted to put this on your radar.

**Comment by kanongil** [comment]
Thanks, this should already be handled by my incoming patch. Just need to create a test or two for this so we don't regress.

**Comment by mshustov** [comment]
@kanongil is there ETA for the patch release? Is there anything I can help you with to speed up the release?

**Comment by kanongil** [comment]
I believe I have a fix, but still working on a creating a test that fails with the current version.

ETA for PR is sometimes today.

**Comment by kanongil** [comment]
I managed to create a test case. I have a PR in #4295.
