### ISSUE TITLE
Node 14 Error: write EPIPE

### ISSUE THREAD

**Issue by aaestrada** [hapijs/hapi#4309]
When move my app to node 14.18.1 or node version 14.15.1 i receive errors in the server.

`   err: {
      "type": "Error",
      "message": "write EPIPE",
      "stack":
          Error: write EPIPE
              at internals.end (/path-to-node_modules/@hapi/hapi/lib/transmit.js:322:21)
      "errno": -32,
      "code": "EPIPE",
      "syscall": "write"
    }`

this is the same with @hapi/hapi:20.0.0 or @hapi/hapi: 20.2.1

### How to reproduce this error?
If you ran a capacity test with the below config:

`concurrency: 1000
  ramp-up: 15m
  throughput: 500
`

Blazemeter ui will show you errors like:

`conection refused`, `conection reset` , `server timeout`

The origin of the problem is in the [transmit](https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L322) file Line 322.

And the application logs will show:
`
    err: {
      "type": "Error",
      "message": "write EPIPE",
      "stack":
          Error: write EPIPE
      "errno": -32,
      "code": "EPIPE",
      "syscall": "write"
    } 
    `
    And i'll doing my tests with [this forked](https://github.com/aaestrada/hapi)

_Originally posted by @kanongil in https://github.com/hapijs/hapi/issues/4296#issuecomment-954571808_

**Comment by kanongil** [comment]
Thanks, but I asked you to create an issue, not just say the same thing again.

In order to fix this, we need a lot of more details, and preferably a reproducible test case.

**Comment by aaestrada** [comment]
Now i update let me know if i can do something more to help with these!

**Comment by kanongil** [comment]
Thanks, this helps a bit. From what you describe, it is an issue that can happen under extreme load.

I would still like some more insight into the server config and route that triggers this. Or is it a generic issue?

Also, what are you using for the capacity test?

**Comment by aaestrada** [comment]
> Thanks, this helps a bit. From what you describe, it is an issue that can happen under extreme load.
> Thanks That true! This happen when run a higth capacity tests
> I would still like some more insight into the server config and route that triggers this. Or is it a generic issue?
> Yeah that's happen when stress the server with request
> Also, what are you using for the capacity test? And you say you move to node v14 – from v12?
Also that's true in node 12 looks like my app support but in node 14 fail with the request come up for a lot of time.

I'm using blazemeter to run this capacity test

**Comment by hasanify** [comment]
```
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at PDF.PdfExec [as exec] (C:\Programming Stuff\modbus\firecal\node_modules\html-pdf\lib\pdf.js:156:15)
    at PDF.PdfToFile [as toFile] (C:\Programming Stuff\modbus\firecal\node_modules\html-pdf\lib\pdf.js:85:8)
    at C:\Programming Stuff\modbus\firecal\node_modules\pdf-creator-node\index.js:69:20 {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```


I'm getting the same error and it only occurs when the dataset i pass into the document is relatively large. Does anybody have any solutions?

**Comment by Nargonath** [comment]
@hasanify Can you submit a repro repo with the large document you're sending, please? This way we can reproduce the problem on our end and find the bug if there is one.
