### ISSUE TITLE
Wrong description In documentation about server.decorate 

### ISSUE THREAD

**Issue by seonjl** [hapijs/hapi#4333]
#### Context

* *node version*:  v14.17.6
* *module version*: "@hapi/hapi": "^20.2.1"

### Wrong description In documentation about server.decorate 
 [server.decorate](https://hapi.dev/api?v=20.2.0#-serverdecoratetype-property-method-options/).

There are 5 types in documentation.

'handler' - adds a new handler type to be used in routes handlers.
'request' - adds methods to the Request object.
'response' - adds methods to the Response object.
'server' - adds methods to the Server object.
'toolkit' - adds methods to the response toolkit.

But, only 4 types in [code](https://github.com/hapijs/hapi/blob/master/lib/server.js#L113/).

'handler' 
'request' 
'~~response~~'
'server'
'toolkit'

**Comment by seonjl** [comment]
```js
server.decorate('response', 'test', () => { console.log('this is test') });
```

If i try to decorate using type 'response',
got error like this
```
AssertionError [ERR_ASSERTION]: Unknown decoration type: response
    at internals.Server.decorate (/Users/seonjl/workspace/do-you-know-hapi/node_modules/hapi/lib/server.js:113:14)
    at Object.register (/Users/seonjl/workspace/do-you-know-hapi/lib/api/index.js:16:9)
    at internals.Server.register (/Users/seonjl/workspace/do-you-know-hapi/node_modules/hapi/lib/server.js:453:35)
    at Object.exports.compose (/Users/seonjl/workspace/do-you-know-hapi/node_modules/glue/lib/index.js:48:22)
    at startServer (/Users/seonjl/workspace/do-you-know-hapi/index.js:40:29)
    at Object.<anonymous> (/Users/seonjl/workspace/do-you-know-hapi/index.js:55:1)
```

**Comment by devinivy** [comment]
Thanks for the report!  This should be supported as of hapi v19.2.0 in #4077.  Here's a test: https://github.com/hapijs/hapi/blob/e4ef336ea0811ea986de1095f185f5f94fe1de6b/test/server.js#L400-L426

Could you double-check which specific version of hapi you have installed?

**Comment by seonjl** [comment]
my hapi version was 20.2.1

**Comment by devinivy** [comment]
I am attempting a reproduction case here with v20.2.1, and I am not able to.  I am closing this issue, but if you can provide a complete example that reproduces the issue we'll be happy to reopen 👍 

https://runkit.com/devinivy/62526506976473000896aa4e
