### ISSUE TITLE
server abnormal exit 

### ISSUE THREAD

**Issue by shavingha** [hapijs/hapi#4368]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: v16.15
* *module version with issue*: "@hapi/hapi": "20.2.2",
* *last module version without issue*: NA
* *environment* (e.g. node, browser, native):  windwos 10
* *used with* (e.g. hapi application, another framework, standalone, ...): nodejs
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?
I send a simple post data to server,  set a wrong content-type, server will down.

```js
const some = 'properly formatted code example';
```
POST data like this:
POST /test HTTP/1.1\r\n
Host: localhost:8080\r\n
User-Agent: UnityPlayer/2021.2.6f1 (UnityWebRequest/1.0, libcurl/7.75.0-DEV)\r\n
Accept: */*\r\n
Accept-Encoding: deflate, gzip\r\n
Content-Type: application/json\r\n
X-Unity-Version: 2021.2.6f1\r\n
Content-Length: 2\r\n
\r\n
%7

hapi server code:
```js
'use strict';
const Hapi = require('@hapi/hapi');
const init = async () => {
    const server = Hapi.server({
        port: 8080,
        host: 'localhost',
    });
    server.route({
        path: '/test',
        method: 'POST',
        handler: (req) => {
            return 'test echo';
        },
    });
    await server.start();
    console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

init();
```
#### What was the result you got?
Error: Unknown error
    at new module.exports (E:\program\TsProj\server\node_modules\@hapi\hoek\lib\error.js:23:19)
    at Object.module.exports [as assert] (E:\program\TsProj\server\node_modules\@hapi\hoek\lib\assert.js:21:11)
    at Response._marshal (E:\program\TsProj\server\node_modules\@hapi\hapi\lib\response.js:566:14)
    at exports.content (E:\program\TsProj\server\node_modules\@hapi\hapi\lib\headers.js:41:24)
    at Object.internals.marshal (E:\program\TsProj\server\node_modules\@hapi\hapi\lib\transmit.js:41:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.internals.fail (E:\program\TsProj\server\node_modules\@hapi\hapi\lib\transmit.js:52:9)
    at async Object.exports.send (E:\program\TsProj\server\node_modules\@hapi\hapi\lib\transmit.js:23:13)
    at async Request._reply (E:\program\TsProj\server\node_modules\@hapi\hapi\lib\request.js:457:9)
server cannot catch the exception, process exit.

#### What result did you expect?
discard the error request, and continue http service.

**Comment by Nargonath** [comment]
Thank you for the report @shavingha. IMO this issue is related to #4363 as in both cases the error comes down to a faulty header. I'm closing this issue in favour of #4363. If that was a mistake, we'll reopen this one.
