### ISSUE TITLE
Issue with handlebars at runtime errors are coming

### ISSUE THREAD

**Issue by bandlachiranjeevi** [hapijs/hapi#4453]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version with issue*: 
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js
at compileInput (/usr/test/webapp/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:508:19)

 at ret (/usr/test/webapp/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:517:18)

  at Object.renderer [as template] (/usr/test/webapp/node_modules/@hapi/vision/lib/manager.js:102:40)

at /usr/test/webapp/node_modules/@hapi/vision/lib/manager.js:417:22

Debug: internal, implementation, error 

Error: Parse error on line 912:
...rve" >{{{Description} }}

Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'INVALID': Parse error on line 912:

Getting above errors when I ran the app in azure app service. from locally it is fine no errors found.

```

**Comment by bandlachiranjeevi** [comment]
Below versions used :

 "@hapi/hapi": "^21.3.0",
      "@hapi/inert": "^7.1.0",
      "@hapi/vision": "^7.0.1"
"handlebars": "^4.7.7",

**Comment by Marsup** [comment]
The error shows a pretty clear mistake in your closing brackets, as mentioned in the error codes. Have you tried fixing that?
