### ISSUE TITLE
Hapi.Types is undefined

### ISSUE THREAD

**Issue by toddhickerson** [hapijs/hapi#761]
var S = Hapi.Types.String;
                  ^
TypeError: Cannot read property 'String' of undefined

Examples (validation.js) and documentation need to be updated if this is a change for 1.0.0.

**Comment by jbarros35** [comment]
Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\jlopesde\node\express\myapp\routes.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Its not working. please reopen.

**Comment by hueniverse** [comment]
You need to npm install joi yourself.
